APP_COMMIT = "8ed57cbde2bf051c990ec5d1dcbf1178e98fa8d8"

MODULES = [
    {
        "number": 0,
        "title": "Start Here",
        "blurb": "How the course works, how Orange Plan AI helps, and the line between teaching, walkthroughs, and Build Your Plan.",
        "lessons": ["0.1", "0.2"],
        "captures": [],
        "build": "Know the course sequence, the US-versus-non-US boundary, the AI tools, and the no-secrets rule.",
        "checkpoint": [
            "You know the course is taught in order but implemented through the owning Build Your Plan area.",
            "You know teach lessons make decisions and walkthroughs perform the clicks.",
            "You have run one useful AI review and know where the daily report and AI export live.",
            "You can state what never goes into an AI tool.",
        ],
    },
    {
        "number": 1,
        "title": "Foundation",
        "blurb": "Replace the rough onboarding estimate with real personal details, accounts, current holdings, and assumptions you can defend.",
        "lessons": ["1.1", "1.2", "1.3"],
        "captures": ["1.4"],
        "build": "An honest current position and a reviewed baseline model.",
        "checkpoint": [
            "Personal details are accurate.",
            "Every real account and custody location is listed.",
            "Current holdings match the source statements.",
            "You know how new activity differs from historical tax reconstruction.",
            "The growth and inflation assumptions were reviewed deliberately.",
            "Build Your Plan shows Foundation complete.",
        ],
    },
    {
        "number": 2,
        "title": "Cash Flow + Reserve",
        "blurb": "Find a surplus the household can reliably move, size the cash Reserve, and add the expected future changes the plan should already know about.",
        "lessons": ["2.1", "2.2", "2.3", "2.4"],
        "captures": ["2.5"],
        "build": "A believable monthly surplus, a funded-or-funding Reserve, and expected life events in the baseline.",
        "checkpoint": [
            "Normal spending and bare-bones spending are separate.",
            "The surplus is believable and sustainable.",
            "Orange Plan calculated the Reserve target from the selected basis and months.",
            "The monthly Reserve build amount is saved.",
            "Expected life events are in the baseline and hypotheticals are in Scenarios.",
            "College funding has a commitment and source plan when it applies.",
        ],
    },
    {
        "number": 3,
        "title": "Allocation + Next-Dollar",
        "blurb": "Choose the Bitcoin allocation you can hold, assign every major account a job, and direct the investable surplus into the right accounts and holdings.",
        "lessons": ["3.1", "3.2", "3.3", "3.4"],
        "captures": ["3.5"],
        "build": "A target allocation, account timeframes, and a contribution plan for what changes now and after the Reserve is full.",
        "checkpoint": [
            "The Bitcoin target survives the dollar drawdown test.",
            "Major accounts have Reserve, Bridge, or Legacy jobs.",
            "The target mix and drift band are saved.",
            "The employer match and contribution destinations are modeled correctly.",
            "Each contribution row says what the money buys.",
            "External payroll, transfer, and purchase changes are listed.",
            "The extra-debt claim is clearly provisional until Module 4.",
        ],
    },
    {
        "number": 4,
        "title": "Debt Strategy",
        "blurb": "Decide the job of every debt, set the extra-payment claim, and return that decision to the contribution waterfall.",
        "lessons": ["4.1"],
        "captures": ["4.2"],
        "build": "Current debt terms, a job for every debt, and a final extra-payment amount reflected in Cash Flow Routing.",
        "checkpoint": [
            "Every active debt has a current balance, rate, and payment or loan-specific terms.",
            "You understand payment capacity and balance-sheet leverage as separate lenses.",
            "Every debt has a job and a reason.",
            "Any Bitcoin-backed loan has written operating triggers.",
            "Extra debt is reflected in Cash Flow Routing.",
            "The contribution plan was rechecked after the debt decision.",
        ],
    },
    {
        "number": 5,
        "title": "Tax Strategy",
        "blurb": "Clean up basis, understand the tax buckets and low-income window, and model the few moves worth taking to a tax professional.",
        "lessons": ["5.1", "5.2"],
        "captures": ["5.3"],
        "build": "Usable lot history, a tax-window roadmap, and a professional handoff packet.",
        "checkpoint": [
            "Missing basis is visible and never silently invented.",
            "Transfers and duplicate imports are reconciled.",
            "The taxable, tax-deferred, and Roth mix is understood.",
            "A conversion or withdrawal range is modeled when relevant.",
            "Harvesting candidates and the 8949 export are saved.",
            "Current-year questions are ready before the calendar deadline.",
        ],
    },
    {
        "number": 6,
        "title": "Retirement Income",
        "blurb": "Build the spending number, income floor, portfolio-funded gap, Bridge years, withdrawal strategy, and annual spending rules.",
        "lessons": ["6.1", "6.2", "6.3"],
        "captures": ["6.4"],
        "build": "A retirement paycheck strategy with accessible Bridge funding and an applied withdrawal order.",
        "checkpoint": [
            "Retirement spending, healthcare, and irregular costs are honest.",
            "The income floor and portfolio-funded gap can be stated from memory.",
            "Bridge years and accessible funding are verified.",
            "Social Security timing was compared when material.",
            "A withdrawal strategy is applied and understood.",
            "Sell, borrow, or hold remains a preview unless intentionally applied.",
            "The first full confidence run is deferred until Module 9.",
        ],
    },
    {
        "number": 7,
        "title": "Custody",
        "blurb": "Choose a custody level, prove recovery, harden the accounts, and remove the largest single point of failure without storing secrets in the plan.",
        "lessons": ["7.1", "7.2", "7.3"],
        "captures": ["7.4", "7.5"],
        "build": "A tested custody process, one major failure point fixed, and a no-secrets checklist with an encrypted plan backup.",
        "checkpoint": [
            "Custody level is chosen for the amount and household.",
            "Hardware recovery is proven or clearly outstanding.",
            "The top single point of failure has an owner and deadline.",
            "Important accounts and email are hardened.",
            "No seed, key, passphrase, or PIN is stored in the app or course notes.",
            "An encrypted backup of the plan data exists.",
        ],
    },
    {
        "number": 8,
        "title": "Estate + Inheritance",
        "blurb": "Give the right people legal authority, align it with the custody process, create the family handoff, and transfer the risks the current stack cannot absorb.",
        "lessons": ["8.1", "8.2", "8.3", "8.4"],
        "captures": ["8.5"],
        "build": "An executor path, legal-document plan, no-secrets heir letter and packet, communication backstop, and insurance gap audit.",
        "checkpoint": [
            "Executor and backup are chosen and contacted.",
            "Baseline legal documents and beneficiary forms have a clear status.",
            "Legal authority and technical recovery are mapped together.",
            "Heir letter and executor packet contain no secrets.",
            "The communication backstop is armed and tested when applicable.",
            "Insurance gaps are documented for licensed review.",
        ],
    },
    {
        "number": 9,
        "title": "Finish, Test + Maintain",
        "blurb": "Close every Build Your Plan area, run the first full confidence check, test decisions separately, save the report, and establish the monthly and annual rhythm.",
        "lessons": ["9.1", "9.2"],
        "captures": ["9.3"],
        "build": "A completed baseline, saved confidence target and retirement date, one tested scenario, yearly report, encrypted backup, and review calendar.",
        "checkpoint": [
            "Every Build Your Plan area is intentionally complete.",
            "The first full 1,000-path confidence result is saved.",
            "The confidence target and earliest date are understood together.",
            "The retirement operating target and guardrail policy are saved.",
            "One scenario was tested without corrupting the baseline.",
            "Monthly and annual review dates are on the calendar.",
            "The yearly report and encrypted backup are saved.",
            "Only one to three next actions remain.",
        ],
    },
]

CORE_FILENAMES = {
    "0.1": "00-1_how-to-use-this-course.md",
    "0.2": "00-2_how-to-use-orange-plan-ai.md",
    "1.1": "01-1_what-to-gather-before-you-build-the-plan.md",
    "1.2": "01-2_the-three-layers-of-a-plan-and-setting-your-assumptions.md",
    "1.3": "01-3_what-the-onboarding-retirement-age-actually-means.md",
    "1.4": "01-4_WALKTHROUGH_foundation.md",
    "2.1": "02-1_find-the-surplus-your-plan-can-actually-use.md",
    "2.2": "02-2_size-your-cash-reserve-in-months-of-spending.md",
    "2.3": "02-3_add-the-future-changes-your-plan-should-expect.md",
    "2.4": "02-4_optional-decide-how-much-college-help-you-are-funding.md",
    "2.5": "02-5_WALKTHROUGH_cash-flow-reserve-life-events.md",
    "3.1": "03-1_set-the-bitcoin-allocation-you-can-actually-hold.md",
    "3.2": "03-2_give-each-dollar-a-job-before-choosing-the-investment.md",
    "3.3": "03-3_build-the-contribution-waterfall-for-every-new-dollar.md",
    "3.4": "03-4_put-the-right-holdings-inside-the-right-accounts.md",
    "3.5": "03-5_WALKTHROUGH_route-the-investable-surplus.md",
    "4.1": "04-1_decide-what-every-debt-should-do.md",
    "4.2": "04-2_WALKTHROUGH_debt-strategy.md",
    "5.1": "05-1_cost-basis-know-what-you-paid-before-you-plan-a-sale.md",
    "5.2": "05-2_use-the-tax-buckets-and-low-income-window-on-purpose.md",
    "5.3": "05-3_WALKTHROUGH_tax.md",
    "6.1": "06-1_build-spending-income-floor-gap-and-bridge.md",
    "6.2": "06-2_choose-withdrawal-order-and-refill-rule.md",
    "6.3": "06-3_use-plan-confidence-and-guardrails-to-adjust-spending.md",
    "6.4": "06-4_WALKTHROUGH_retirement-paycheck.md",
    "7.1": "07-1_choose-a-custody-setup-your-household-can-recover.md",
    "7.2": "07-2_set-up-a-hardware-wallet-and-prove-recovery.md",
    "7.3": "07-3_fix-single-points-of-failure-and-harden-accounts.md",
    "7.4": "07-4_DEMO_hardware-wallet-and-exchange-hardening.md",
    "7.5": "07-5_WALKTHROUGH_document-custody-status.md",
    "8.1": "08-1_choose-who-is-in-charge-and-put-the-legal-baseline-in-place.md",
    "8.2": "08-2_align-legal-authority-with-technical-recovery.md",
    "8.3": "08-3_write-the-heir-letter-and-create-the-backstop.md",
    "8.4": "08-4_use-insurance-for-risks-the-stack-cannot-carry.md",
    "8.5": "08-5_WALKTHROUGH_family-handoff.md",
    "9.1": "09-1_keep-the-plan-current-without-rebuilding-it.md",
    "9.2": "09-2_test-decisions-and-read-the-finished-plan.md",
    "9.3": "09-3_WALKTHROUGH_finish-test-review-and-save.md",
}

DICTATED = {"0.1", "1.1", "1.2", "2.2"}
OPTIONAL = {"2.4"}

ADVANCED_ORDER = [
    "A1.1", "A3.1", "A4.1", "A4.2", "A5.1", "A5.2", "A5.3",
    "A6.1", "A6.2", "A7.1", "A7.2", "A7.3", "A7.4", "A8.1",
]

ADVANCED_FILENAMES = {
    "A1.1": "A1-1_how-orange-plan-models-bitcoin.md",
    "A3.1": "A3-1_price-context-before-a-large-bitcoin-move.md",
    "A4.1": "A4-1_borrow-against-bitcoin-without-liquidation.md",
    "A4.2": "A4-2_four-ways-debt-can-strengthen-a-plan.md",
    "A5.1": "A5-1_rmd-pressure-and-roth-conversions.md",
    "A5.2": "A5-2_harvest-bitcoin-losses-and-gains.md",
    "A5.3": "A5-3_state-taxes-and-relocation.md",
    "A6.1": "A6-1_health-coverage-before-medicare.md",
    "A6.2": "A6-2_sell-borrow-or-hold.md",
    "A7.1": "A7-1_advanced-custody.md",
    "A7.2": "A7-2_what-self-custody-asks-of-you.md",
    "A7.3": "A7-3_avoid-custody-concentration.md",
    "A7.4": "A7-4_utxos-dust-consolidation-and-addresses.md",
    "A8.1": "A8-1_do-you-need-a-trust.md",
}

PROFESSIONAL_GATES = {
    "tax": "Targeted CPA or EA review before publishing current-year tax examples and execution guidance.",
    "custody": "Exact device, firmware, provider, and recovery process verified before setup-specific footage.",
    "insurance": "Licensed insurance professional reviews policy mechanics and contract-specific claims before publication.",
    "estate": "State-licensed estate attorney reviews state-specific authority, trust, and executor material before publication.",
}

VISUALS = {
    "2.1": ["Cash Flow by Stage: Working → Approaching → Retired", "Keep / Cut / Reduce", "Housing / car / location big levers"],
    "2.2": ["Bare-bones essentials × months = Reserve target", "Reserve-size dial factors", "Working Reserve versus retirement gap Reserve"],
    "2.3": ["Baseline life-event examples", "Expected event versus Scenario decision split"],
    "2.4": ["College commitment and funding-source stack"],
    "3.1": ["Bitcoin path: Foundation / Integration / Optimization / Sovereign", "Dollar net-worth hit from a 75% Bitcoin drawdown"],
    "3.2": ["Reserve / Bridge / Forever jobs", "Low / moderate / high-volatility paths"],
    "3.3": ["Contribution waterfall", "Bridge path versus Forever path"],
    "3.4": ["Taxable / tax-deferred / tax-free account jobs", "Direct Bitcoin / ETF / no-Bitcoin account filter"],
    "4.1": ["Debt tolerance before ratios", "Debt ledger with one job per row"],
    "5.1": ["Bitcoin lot table: same sale, different basis, different tax"],
    "5.2": ["Three tax buckets", "Low-income bracket window", "Gain and loss harvesting"],
    "6.1": ["Spending / income floor / gap", "Annual cash-flow map", "Bridge-years timeline"],
    "6.2": ["Income waterfall", "Reserve ← Bridge ← Forever draw-and-refill"],
    "6.3": ["Deterministic onboarding line versus 1,000 plan paths", "60 / 80 / 95 guardrails with ±10% cap"],
    "7.1": ["Five custody questions", "Custody levels 1–4"],
    "7.2": ["Device-specific six-step recovery process"],
    "7.3": ["The only-one single-points-of-failure list"],
    "8.1": ["Capable / Available / Trustworthy executor"],
    "8.2": ["Passphrase single-sig and 2-of-3 multisig as separate diagrams"],
    "8.3": ["Heir-letter include / never-include", "Check-in → waiting period → safe letter delivered"],
    "8.4": ["Insurance coverage-gap audit"],
    "9.1": ["Five-minute monthly maintenance loop"],
    "9.2": ["Baseline versus one named Scenario", "Report reading order: Position → Trajectory → Risk → Actions"],
}
