#!/usr/bin/env python3
"""Bounded alignment/synchronization of the already-written Allocation revision.
No app access; no teaching generated from templates. Remove before integration.
"""
from pathlib import Path
import subprocess, hashlib
ROOT=Path(__file__).resolve().parents[1]
BASE='64d053641ad36f620174c79a3e5d2338ea73b9b7'
P2='scripts/04-2_set-a-bitcoin-target-the-household-can-hold.md'
P3='scripts/04-3_match-the-money-to-when-you-will-use-it.md'
P1='scripts/04-1_read-the-same-portfolio-in-four-useful-ways.md'
P7='scripts/04-7_tell-each-account-what-to-buy-and-finish-the-outside-actions.md'
W='scripts/working/W04_route-contributions-into-usable-accounts-and-intended-holdings.md'
def old(p):return subprocess.check_output(['git','show',BASE+':'+p],cwd=ROOT)
def put(p,t):(ROOT/p).write_text(t.rstrip()+'\n',encoding='utf-8')
def one(t,a,b):
    if t.count(a)!=1:raise ValueError('Bounded replacement differs: '+a[:70])
    return t.replace(a,b,1)
def content(p):return (ROOT/p).read_text()
initial=set(subprocess.check_output(['git','diff',BASE,'--name-only','--','scripts'],cwd=ROOT).decode().splitlines())
if initial!={P2,P3}:raise ValueError('Unexpected starting script changes')
for p in (ROOT/'scripts').rglob('*.md'):
    rel=str(p.relative_to(ROOT))
    if rel not in initial and p.read_bytes()!=old(rel):raise ValueError('Untargeted script changed')

t=content(P1)
t=one(t,'Then we\'ll choose the Bitcoin target with the rest of the household in view.',"Then we'll decide the role Bitcoin should play and size the positions for the different years when the money will be used.")
put(P1,t)
t=content(P7)
t=one(t,'For the current example, a 60% Bitcoin target corresponds to $784,200 of the $1,307,000 group.',"Back with Alex and Morgan, the separate 60/34/6 comparison uses their $1,307,000 group. It isn't the $500,000 timeframe illustration from Lesson 4.3. Their 60% Bitcoin comparison corresponds to $784,200.")
t=one(t,"To finish the session, you should be able to follow one contribution from the available money, to its purpose, to the account, and finally to the investment. Then explain how it fits with the other accounts and what changes after the next funding milestone.","To finish the session, check each contribution you're planning—not just one example. Does it have an affordable amount, a job and timeframe, a receiving account, and an investment instruction? Then check the combined holdings against the target you chose.\n\nBe clear about what changes now, what waits for a debt payoff or a funded Reserve, and what can stay as it is. A contribution that starts later still needs its own condition and funding source. You can leave an outside action pending, but it should be a specific action, not an investment decision we never finished.")
put(P7,t)

chapters=r'''#### Chapter 2, after 4.2 — identify Bitcoin's intended role

**Show:** The original four-path slide and the already-reviewed current exposure, not a target editor. Foundation 1–5%, Integration 10–20%, Optimization 25–50%, Sovereign 50%+ are illustrative conversation ranges with gaps/overlap, not automatic app classifications or mandatory per-account percentages.

**Narration:**

“Which description fits what you want Bitcoin to do? We aren't choosing every account's percentage yet. First, explain whether you're learning with a small position, integrating it with other investments, or using it as the main long-term holding.”

“Now compare that intention with what you own. Did the current mix come from a choice you still support, or from price changes and old contribution instructions? That tells us what needs a decision in the next step.”

Record the explanation in an existing supported note or course worksheet only if useful. Do not invent a new suitability questionnaire, score or required homework file. No custody tier, target save, 60/34/6 adoption or replay of the Debt drawdown calculation occurs here.

**Screen checks:** Current exposure uses the same denominator as chapter 1. The path slide is teaching, not a feature or recommendation generated by the app. No financial write is needed to finish this brief orientation.

**Member finish:** A clear intended role and any current-versus-intended mismatch. Continue to sizing before finalizing the target.

#### Chapter 3, after 4.3 — size by timeframe, combine, then check the target

**Show:** Deck Steps 3–5 in their original reasoning order: money's timeframe/job → position sizes → check the resulting funding plan. Use the existing Reserve decision and named expected needs. Distinguish when the money will be spent from the account's access rules; detailed account selection remains chapter 5.

**Narration:**

“Start with the amount needed for each job. The Reserve already has a target. An approaching purchase has a date and a funding need. The longer-runway money can have a different mix because it isn't all being spent at the same time.”

**Show:** A separate, labeled $500,000 mechanics graphic—not a Reed record or an app result. Near-term $50,000 all cash; Bridge $100,000 with $20,000 BTC/$50,000 stocks/$30,000 cash; long-runway $350,000 with $280,000 BTC/$70,000 stocks. The $30,000 Bridge cash is an assumed amount chosen for that example's first Bridge payments, not a second claim on the near-term $50,000. The job amounts and weights are illustrative choices, not verified need calculations or recommendations.

Reveal each group as it is discussed. Do not show a wall of amounts or require the member to copy this portfolio.

**Narration:**

“We're comparing different investment choices for different jobs. The near-term money has no Bitcoin. The Bridge has a smaller Bitcoin position alongside stocks and cash for its earlier payments. Most of this example's Bitcoin sits in the long-runway portion.”

**Show:** Combine dollars, not the simple average of group percentages: BTC $300,000 (60%), stocks $120,000 (24%), cash $80,000 (16%). All rows sum to $500,000.

**Narration:**

“Add the dollar positions first, then divide by the total. These choices produce 60% Bitcoin overall. That doesn't mean every account, or even every timeframe, holds 60% Bitcoin.”

**Show:** Change only the long-runway mix to 60% BTC / 40% stocks. Long BTC falls to $210,000 and stocks rise to $140,000; aggregate BTC $230,000 (46%), stocks $190,000 (38%), cash unchanged $80,000 (16%). This is a $70,000 shift within the long-runway group, not a trade already made.

**Narration:**

“Now we've isolated the decision. Should another $70,000 of the long-runway money be in Bitcoin or stocks? We haven't taken money from the Reserve or changed the Bridge. We can see which dollars the new percentage would actually change.”

**Show:** Check the earliest payment against actual available funding once. Identify any need to sell, delay, reduce spending, or revise the relevant position. Stock holdings are not treated as cash and the example is not certified safe by its allocation. Do not repeat a general lesson about tolerating a lower balance.

**Narration:**

“Before keeping the target, look at the first payments. Which money will provide them? If the answer depends on selling investments at a favorable price, decide whether to change the funding or accept a flexible date or amount. This check is about the plan we've built.”

**Return to the Reed plan explicitly:** The real course source remains $1,307,000 with $728,000 BTC exposure. Its 60/34/6 target is a different hypothetical comparison, not derived from the separate 60/24/16 example. Identify intended uses and relevant input gaps before adopting it. Do not divide the source's assets into unprovided timeframe balances or manufacture a final qualifying allocation.

Read actual same-scope Current and Target controls only after the approved build is available. Six percent of the Reed subset is $78,420, not a new Reserve need. Its $43,200 target and $32,000 assignment keep their meanings. The broader $75,000 cash/Treasury category includes other jobs and must not all be counted as uncommitted liquid Reserve money.

**Screen checks:** No per-timeframe sliders, partial-designation controls, second ledger, automatic target roll-up, account transfers or plan improvements are assumed to ship. The arithmetic graphic remains outside the app. Use verified app features to inspect the same accounts and an explicitly chosen comparison, and demonstrate actual preview/cancel/save/readback only when authorized and supported. Saving a target never implies a trade. Unsupported funding attribution stays a stated limitation.

**Member finish:** Explain job amounts, position sizes and the combined target; identify the first funding/access issue and the specific sizing change that addresses it. An unverified Reed input remains open. The member can complete this method with their supported facts without copying the fictional weights.

'''
t=content(W)
a=t.index('#### Chapter 2, after 4.2')
b=t.index('#### Chapter 4, after 4.4')
t=t[:a]+chapters+t[b:]
t=one(t,'**Member finish:** A receiving account with a reason it fits, or one concrete missing fact before it can be used.', '''**Additional access verification, only when relevant to the chosen account:** Each adult has a separate timeline. Alex's preferred age 52 is a choice, not a model result; the usual 59½ landmark is 7.5 years later for Alex, while Morgan is two years younger. The taxable $575,000 subset includes bills and Reserve; the retirement $732,000 subset is not all usable on identical terms. Check any early-access route, plan permission, ordinary tax and additional-tax exception separately before relying on it. HSA/529 retain their dedicated uses. This is a verification checklist here, not an extended detour in the sizing lesson. Relevant detailed withdrawal instruction belongs in Retirement Income.

**Member finish:** A receiving account with a reason it fits, or one concrete missing fact before it can be used.''')
t=one(t,'**Show:** $1,307,000 × 60% = $784,200 target exposure versus $728,000 current; gap $56,200.', '**Show:** Return explicitly to the Reed 60/34/6 comparison, distinct from the $500,000 mechanics example used in chapter 3. $1,307,000 × 60% = $784,200 target exposure versus $728,000 current; gap $56,200.')
t=one(t,'**Member finish:** Trace one contribution from affordable money through its job, account and holding to the outside action still needed. A missing sale record becomes the focused handoff to Tax, not a made-up basis.', '**Member finish:** Complete and read back every current and conditional future contribution instruction: affordable amount, job/timeframe, receiving account, tax treatment, intended investment, source/start condition and actual outside action. Include what does not need to change. A missing sale record becomes a specific Tax question, not invented basis or an unresolved allocation decision marked done.')
t=one(t,'The member can explain the portfolio and target, identify which money is for earlier and later needs, reconcile the contribution amounts, select usable accounts and tax treatment, and state what each contribution buys.', "The member can start with the current portfolio, state Bitcoin's intended role, size positions for the spending jobs, combine them into a target, fit current contributions, choose usable accounts and tax treatment, and finish each investment instruction. The four-path orientation does not prematurely save a target. The drawdown check validates the chosen funding once rather than replacing the sizing method.")
t=one(t,'This is one replacement W04 with the existing eight chapters, not another course structure or alternate walkthrough.', 'This is one W04 with the existing eight chapters. The subsequent section-level correction replaces chapters 2–3 and aligns the chapter 5/7/8 handoffs; it does not add a competing walkthrough.')
put(W,t)

p='tools/guided_course.py';data=(ROOT/p).read_bytes()
if hashlib.sha1(b'blob '+str(len(data)).encode()+b'\0'+data).hexdigest()!='4d12ba0e70884c418e3b5dd747a6fec6306f3d03':raise ValueError('Generator differs')
t=data.decode()
anchor="    eq('80 percent Bitcoin group isolated 70 percent decline',D('.8')*D('.7'),D('.56'))"
extra="""    # Separate 4.3 sizing illustration: never mutate or calibrate the Reed fixture.
    near=(D(0),D(0),D(50000)); bridge=(D(20000),D(50000),D(30000)); long=(D(280000),D(70000),D(0))
    eq('timeframe example near-term assigned',sum(near),50000)
    eq('timeframe example Bridge assigned',sum(bridge),100000)
    eq('timeframe example long-runway assigned',sum(long),350000)
    combined=tuple(near[i]+bridge[i]+long[i] for i in range(3))
    eq('timeframe example counted once',sum(combined),500000)
    for i,(asset,amount,weight) in enumerate([('Bitcoin',300000,'.60'),('stocks',120000,'.24'),('cash',80000,'.16')]):
        eq('timeframe example '+asset+' dollars',combined[i],amount)
        eq('timeframe example '+asset+' weight',combined[i]/sum(combined),D(weight))
    revised_long=(D(210000),D(140000),D(0))
    revised=tuple(near[i]+bridge[i]+revised_long[i] for i in range(3))
    eq('timeframe alternate total unchanged',sum(revised),500000)
    eq('timeframe alternate Bitcoin weight',revised[0]/sum(revised),D('.46'))
    eq('timeframe alternate stock weight',revised[1]/sum(revised),D('.38'))
    eq('timeframe alternate cash unchanged',revised[2],80000)
    eq('timeframe isolated long-runway reallocation',long[0]-revised_long[0],70000)
"""
t=one(t,anchor,anchor+'\n'+extra.rstrip())
put(p,t)

p='HANDOFF.md';t=content(p)
section='''## Allocation section-level correction — finish the decision before moving on

Austin identified that 4.2 repeated drawdown tolerance while the more useful sizing-by-timeframe step was missing. He asked to finish each section rather than proceed through more script batches. The earlier statement that the Allocation replacement was ready to leave for Tax is superseded.

Actual correction: 4.2 now uses the four paths to establish Bitcoin's intended role. The deck's illustrative percentage bands are visible without becoming mandatory ranges or automatic suitability classifications. 4.3 now owns assigning money to timeframes, sizing the holdings, combining the dollar-weighted target, and testing the resulting spending funding once. Early-access mechanics no longer occupy the bulk of that explanation; their feasibility check stays with account choice and detailed retirement instruction. W04 follows the same sequence, with no target save in chapter 2 and the actual target comparison only after sizing in chapter 3. The 4.1 ending and 4.7 return-to-example/finish are aligned.

All seven current lessons and the whole W04 sequence were read for distinct work, not just isolated word quality. 4.4, 4.5 and 4.6 retain their existing narration because the amount, account and tax-election decisions are different jobs. No blanket reapproval of those drafts is asserted.

| Lesson | Distinct job | Original deck anchor |
|---|---|---|
| 4.1 | Read current exposure and identify a mismatch | Step 1 |
| 4.2 | State the intended Bitcoin role | Step 2 |
| 4.3 | Size by timeframe, combine into a target and check funding | Steps 3–5 |
| 4.4 | Fit current contributions and future changes into actual cash flow | Step 6 |
| 4.5 | Select an eligible, usable account with the needed menu | Steps 7 and 9 |
| 4.6 | Compare tax election using the same economic budget | Step 8 |
| 4.7 | Specify purchases and finish each current/future outside instruction | Step 10 |

The original Accounts + Allocation deck's relevant slide text and speaker notes were reread in sequence; the older protocol explicitly supports sizing Bitcoin differently across Bridge and Forever. This is not a claim of original audio listening or complete visual deck inspection. The current wording, examples and latest owner direction take precedence over historical interface claims and categorical guarantees. No real client story or data is introduced.

The new $500,000 illustration is separate from the Reed fixture: $50,000 near-term cash; $100,000 Bridge at 20/50/30; $350,000 long-runway at 80/20/0; aggregate 60/24/16. A second comparison changes only long-runway to 60/40/0, producing aggregate 46/38/16. These are proposed example assumptions demonstrating the method, not a recommendation or an approved Reed decision. The existing Reed 60/34/6 target and future contribution illustration remain explicitly separate. The existing arithmetic checker verifies the new sums; no new quality-scoring framework is added.

A narrow SEC Investor.gov check supports the horizon/allocation mechanism, not the example weights. Final tax/access, app and recording evidence remains separate. All other sessions, source-material, fixture, toolkit, capture records and historical cleanup are preserved.

'''
t=one(t,'## Next\n',section+'## Next\n')
start=t.index('Continue with Tax and W05, one complete lesson and its matching working chapter at a time.')
end=t.index('\n\nUse existing `scripts/`',start)
t=t[:start]+'''Keep Allocation as the current section until the owner is satisfied with this complete teaching-and-walkthrough sequence. Do not start Tax merely because the script files have been rewritten. Each subsequent section needs its own deck-based decision chain, an actual worked explanation, and matching walkthrough before it is presented as ready for owner review. Writing, owner acceptance and filming remain different states. This does not require another course-architecture reset or new workbook. The earlier sessions and conditional Advanced library still retain their stated review/repair needs. No background continuation or whole-course completion is claimed.'''+t[end:]
put(p,t)
p='FINALIZATION-STATUS.md';t=content(p)
t=one(t,'| 4.1–4.7 | Seven full Allocation replacements written; integrated voice/judgment review remains pending. |', '| 4.1–4.7 | Current section under review. Owner feedback on redundant 4.2 led to a concise four-path lesson, a full timeframe-sizing 4.3 and aligned section handoffs. Owner acceptance remains open. |')
t=one(t,'| W04 chapters 1–8 | One narrated recording plan per chapter; exact account, tax, calculation and save behavior remain pending. |', '| W04 chapters 1–8 | Sequence aligned to role → sizing → target → contributions → account/election → purchases. Final account/app results and recording remain unverified. |')
t=one(t,'Next is Tax and W05; the opening sessions, conditional Advanced lessons and all other unrepaired components also remain on the repair list.', 'Finish the current Allocation section with Austin before moving to Tax and W05. The opening sessions, conditional Advanced lessons and all other unrepaired components also remain on the repair list. A written section needs a coherent decision chain and paired walkthrough, not merely every file touched.')
put(p,t)
p='README.md';t=content(p)
t=one(t,'The newest replacement session is [Allocation and the next dollar](modules/04.md),', '**Current section: Allocation, still under owner review.** The latest correction makes 4.2 the four Bitcoin paths and 4.3 the actual timeframe-sizing method; W04 and the final contribution instructions follow the same sequence. We are not advancing to Tax before finishing this section.\n\nThe newest replacement session is [Allocation and the next dollar](modules/04.md),')
put(p,t)

expected={P1,P2,P3,P7,W}
actual=set(subprocess.check_output(['git','diff',BASE,'--name-only','--','scripts'],cwd=ROOT).decode().splitlines())
if actual!=expected:raise ValueError('Wrong final canonical scope')
for p in (ROOT/'scripts').rglob('*.md'):
    rel=str(p.relative_to(ROOT))
    if rel not in expected and p.read_bytes()!=old(rel):raise ValueError('Untargeted canonical content changed')
print('Aligned Allocation decision chain. Section acceptance and filming remain open.')
