# Temporary, individually authored edits. Removed before integration into main.
# Each replacement is bounded to Read aloud; technical notes and prior safeguards remain.
EDITS = [
('0.1',
 "We'll work through one decision at a time. I'll explain it, show you an example, and then help you do the same in your plan. Each section builds on the one before it.",
 "We'll work through one decision at a time. I'll explain the choices and show why a household might prefer one. Then you'll compare the choices that fit your life. Your answer does not have to match the example.\n\nUse a calculator and pause when you need to. This is not a test of mental math. What matters is knowing which numbers to use, what the result means, and what you would do with it."),
('0.1',
 "First, we'll get a believable starting picture. Then we'll establish what money is available, size the reserve, and decide what to do with debt. Allocation turns those decisions into a portfolio and contribution plan. Tax and retirement income explain how the money can eventually reach your bank account. Custody, family instructions, and maintenance make the plan usable beyond today.",
 "First, we'll get a believable starting picture. Then we'll work out what money is available, how much cash to keep for problems, and what to do with debt. Allocation means choosing your investment mix. That section helps you choose what to own and where new savings go. After that, we'll work out how the money can pay for retirement, how to protect access to your Bitcoin, and how to keep the plan useful as life changes."),
('1.2',
 "An account tells us who owns the money and the rules around it. A holding is the investment inside. A Roth IRA can hold stocks, a Bitcoin fund, cash, or other permitted investments. Knowing the account's name doesn't tell us which one you have.",
 "An account tells us who owns the money and the rules around it. A holding is the investment inside. An IRA is an individual retirement account. A 401(k) is a workplace retirement plan. You can copy the account type from your statement; you don't need to choose a new type now. A Roth IRA can hold stocks, a Bitcoin fund, cash, or other permitted investments. Its name doesn't tell us which investments you have."),
('1.2',
 "Direct Bitcoin has a quantity and a custody location. The wallet describes how you control or access it; Bitcoin is the asset. Keep a clear, non-secret name for each location. A spot Bitcoin fund remains a security in its account. Its dollar exposure can be combined with other Bitcoin exposure later, but it isn't native Bitcoin you can recover using a hardware-wallet backup.",
 "For Bitcoin itself, record how much you own and where you control or access it. That's the custody arrangement. Use a clear name for the location, without private recovery information. A spot Bitcoin fund is different: you own shares in a fund that holds Bitcoin. Those shares give you Bitcoin price exposure, but they are not coins you can recover with your personal wallet backup. Later we'll add the dollar amounts when reviewing your investment mix."),
('1.3',
 "Start with each person's income. Identify the source, amount, and timing. For employment, check whether the field asks for gross income or take-home pay. Your bank deposit is after the deductions on the pay stub. If you enter it as gross income and subtract those deductions again, the result will be wrong.",
 "Start with each person's income. Identify the source, amount, and timing. Gross pay means pay before taxes and other deductions. Take-home pay is what remains after those amounts come out. Match the number to the field being filled. Your bank deposit is already take-home money; subtracting its payroll deductions again would count them twice."),
('1.3',
 "Alex earns $155,000 a year and contributes 6% in the fictional example. That is $775 a month. The employer's stated formula adds another $387.50. We will keep those two sources separate.",
 "Alex earns $155,000 a year and puts 6% into his workplace plan. Six percent means six dollars out of each hundred. On a calculator, $155,000 times 0.06 is $9,300 a year. Divide by twelve, and that is $775 a month. The employer's formula adds another $387.50 a month. Keep his money and the employer's money separate."),
('1.3',
 "Start a retirement-spending estimate based on the life you expect. Some work costs may disappear. Travel, healthcare, or family support may increase. Include the items you know and flag the estimates that need more work. We will build the detailed retirement paycheck later.",
 "You don't have to know your final retirement budget yet. Start with what your life costs now. Subtract costs you expect to stop and add costs you expect to begin. Some work costs may disappear; travel, healthcare, or family support may increase. Keep an uncertain amount marked as an estimate rather than use zero. We will check and improve this first budget as we go."),
('1.4',
 "Before continuing, be able to say what growth path, inflation basis, and horizon your starting plan uses—and why. Keep one less-favorable comparison beside it. Now the first result will mean something: it answers a question under assumptions you deliberately chose.",
 "Before continuing, explain three things: how the investments are assumed to grow, how rising prices affect spending, and how many years the plan needs to cover. That last period is the planning horizon.\n\nYou are not being asked to predict the right return. Start with a model you understand, then compare a slower-growth version. If the answer changes, identify the choice it affects—saving, spending, or work timing. Choosing that response is the decision you control."),
('A1.1',
 "Expected growth is also different from uncertainty around it. A model's volatility, correlations and distribution assumptions affect the range and sequence of outcomes. Don't reduce uncertainty simply to make a desired retirement date pass. Use the current methodology to understand which controls are available and what they change.",
 "Expected growth is different from the range of possible results. Volatility describes how much returns swing. Correlation describes how investments move in relation to each other. The model also makes choices about how often it tests small and extreme changes. Those choices affect the outcomes. Don't make the test easier just to approve a retirement date. Check what the model actually supports before changing those assumptions."),
('1.5',
 "There can also be a difference between a starting projection and a full simulation. A single projected path shows what happens under one sequence of assumptions. A simulation tests many modeled paths. They are related views, but they don't give the same information.",
 "A projection follows one possible future using the assumptions in the plan. A simulation tests many possible futures built from the model's rules. In one, investments do well early. In another, they struggle. The question is whether each tested future can fund the planned spending through the end of the plan."),
('1.5',
 "Here is how to read a simulation percentage. Suppose 790 out of 1,000 modeled paths fund the spending through age 95. That is 79%. The other 210 paths do not fund the full horizon under the tested rules.",
 "Suppose 790 out of 1,000 test futures cover the planned spending through age 95. That is 79%: 790 divided by 1,000, then multiplied by 100. The other 210 do not cover the full period under those rules. When a result is called a confidence level, find out exactly what counted as success in that calculation."),
('1.5',
 "Before moving on, explain what the plan says about your preferred date and which assumption or input needs the next check. The later strategies can wait until we have this starting picture right.",
 "Before moving on, explain what the plan says about the date you want. Pick one input to verify or one real choice to compare. If the facts are right and you prefer the current plan, keeping it is a decision too. You don't need to change something just because an example did."),
('2.4',
 "That is more useful than only looking at whether the retirement date moved. A plan may still show the same retirement timing while asking you to sell an investment or take on a payment you wouldn't be comfortable with.",
 "The retirement date might stay the same even though funding the purchase requires a sale or a loan you wouldn't choose. Read that trade-off before deciding."),
('2.5',
 'It\'s easy to jump straight to, "Should I open a 529 or buy Bitcoin for my kids?" Before we can compare those choices, we need to know what the money is supposed to cover and when it will be needed.',
 'It\'s easy to jump straight to, "Should I open a 529 or buy Bitcoin for my kids?" A 529 is an education savings account with rules and possible tax benefits. Before comparing the accounts or investments, decide what help you want to provide and when the money will be needed.'),
('3.2',
 "Start with the total value of the assets included in your balance sheet. Then compare the total debt with that number. Debt divided by assets gives us the debt-to-assets ratio.",
 "Your assets are the things you own that have value. Your debts are what you owe. A balance sheet lists both. Divide the debt by the value of the assets, then multiply by 100 to get the percentage. That is the debt-to-assets ratio."),
('3.2',
 "For the course illustration, we're using a hypothetical liquidation threshold of 80%. With a fixed debt balance, a loan starting at 50% LTV reaches that line after a 37.5% decline in collateral value. Starting at 25% gives it more room: about a 68.75% decline reaches the same line.",
 "For this example, suppose the lender can sell the collateral at 80% LTV. Picture $50,000 owed against $100,000 of collateral. If that collateral falls to $62,500, the loan is now 80% of its value: $50,000 divided by $62,500. The collateral fell $37,500 from the starting $100,000—a 37.5% decline. The loan balance didn't change.\n\nStarting at 25% LTV gives more room: a 68.75% decline reaches the same assumed 80% line when the debt stays fixed. These are made-up contract terms to explain the math, not a lender's current offer."),
('3.5',
 "Different funding sources bring different questions. You only need to investigate the ones that fit your decision, but I want you to recognize what makes them different.",
 "Before looking at loan types, put two realistic ways to pay for your purchase side by side. For each, note the cash used now, the payment, what remains owed later, and what secures it. That gives the details below a purpose. You don't need to collect an offer for every type of loan; find the terms that matter to your actual comparison."),
('4.1',
 "First, add up what you own across accounts. Looking only at your wallet can understate your Bitcoin exposure when retirement accounts hold Bitcoin funds too.",
 "Your portfolio is the group of investments we're reviewing. Add up what you own across its accounts. Bitcoin exposure means the amount whose value is tied to Bitcoin. Looking only at your wallet misses that exposure when retirement accounts also hold Bitcoin funds."),
('4.3',
 "The deck calls these timeframes Reserve, Bridge, and Forever. The rough zero-to-three, four-to-ten, and ten-plus-year ranges are orientation aids. They aren't rules that every household needs three years of expenses in cash or that an investment becomes safe on a particular anniversary.",
 "We use Reserve, Bridge, and Forever to help think about when money will be used. The rough zero-to-three, four-to-ten, and ten-plus-year ranges are starting guides, not rules. You don't automatically need three years of expenses in cash.\n\nThese are timeframes, not three account types. One brokerage account might hold cash for a purchase and stock funds for much later. First decide what each amount is for. Then we can choose where to hold it."),
('4.3',
 "Together, those jobs need $100,000. They decide to keep it in cash arrangements that will make it available when required. That leaves $400,000 still to position.",
 "The $60,000 Reserve plus the $40,000 purchase need $100,000 in cash arrangements that fit those dates. Start with the $1 million, subtract the $500,000 Bitcoin choice, then subtract this $100,000. There is $400,000 left for the longer-term investments."),
('4.3',
 "That is how we choose the amounts. Start with the bills and commitments, then compare the uncertainty you're willing to accept with the remaining money. There won't be one perfect portfolio for every household.",
 "That is how we choose the amounts. Work out the spending commitments first, then decide what the remaining money needs to provide. If keeping your starting Bitcoin percentage leaves an important bill without funding, revisit that choice too. Compare a different purchase, a later date, another available source, or a smaller Bitcoin position. The percentage is something to test, not a promise that overrides the rest of your life."),
('4.3',
 "Write the purpose and amount beside each part of your portfolio. Choose the investments for those jobs and compare the alternative you're seriously considering. Check any product details you still need before making a purchase.",
 "Now use your own amounts. Write down the money needed for each commitment and what remains for longer-term investing. For that remainder, compare the investments you're seriously considering: what do they own, what do they cost, and what would a bad result mean for you?\n\nExplain your choice without using the example's percentages as the reason. Two households can learn the same method and choose different portfolios. If an existing holding already fits, keeping it is a valid choice."),
('4.4',
 "Start from the cash flow we've already checked. Bring forward the existing employee contribution and the Reserve and extra-debt decisions. We are not reopening those lessons. We are putting their amounts on the same page.",
 "Start with the cash flow you've checked. Put the existing payroll contribution, Reserve funding and extra debt payments on the same page. The next investment must fit alongside them."),
('4.4',
 "For the remaining money, ask which part of the plan needs it. If the years before retirement-account access are short, an accessible destination may help more than another later-retirement contribution. When those years are covered and the goal is much later, the tax-advantaged choices may be more useful.",
 "For any money left, ask which part of the plan is not funded yet. If you don't have enough available for the years before you can use retirement accounts, adding to an accessible account may help more. If those early years are funded and this money is for later, compare the retirement-account choices. We are looking for a shortage of usable money, not simply counting how many years there are."),
('4.5',
 "Start with when you'll need the money. Then check whether the account lets you use it then and offers the investments you intend to buy.\n\nStart with the contribution's job. Is it intended for an early work transition, a later retirement year, or a dedicated expense such as healthcare? Then compare the accounts actually available to you.",
 "Begin with the job of this new saving, which we call a contribution. Is it for an early work change, later retirement, or a specific cost such as healthcare? Compare the accounts you could actually use. Can you get the money when needed? Can the account hold the investment? What costs and tax rules go with it?"),
('4.5',
 "An HSA can be attractive when you are eligible to contribute and the money has a healthcare role. It can combine favorable contribution treatment with tax-free use for qualified medical expenses. You need the coverage eligibility and the records supporting qualified use, not just an account with HSA in its name.",
 "An HSA is a health savings account. If you qualify to contribute, it can give tax benefits when saving and when paying qualified medical expenses—expenses that meet the tax rules. First check whether your coverage makes you eligible, and keep the records for the medical costs you plan to pay from it."),
('4.6',
 "A Roth balance can look attractive because qualified withdrawals are tax-free. A Traditional contribution can look attractive because it may reduce taxable income now. To compare them fairly, we need to account for the tax on both sides.",
 "A withdrawal is money you take out of an account. Qualified means the withdrawal meets the rules for that account's tax benefit; it does not mean every withdrawal from that account is tax-free. Roth can provide tax-free qualified withdrawals. Traditional may reduce the income taxed now. Let's count the tax on both sides before choosing."),
('4.7',
 "A contribution mix may also differ from the portfolio target. You might direct more of the next dollar toward an underweight holding. Prices and the total portfolio change along the way, so don't promise an exact date to reach the target by dividing today's gap by a fixed monthly contribution.",
 "What the next contribution buys may differ from the final mix you want. If you own less of one investment than your target calls for, new money can go toward that gap. Prices and the rest of the portfolio change too, so dividing today's gap by a monthly contribution won't tell you the exact date you'll reach the target."),
('5.1',
 "Cost basis is the amount used to measure what the investment cost you, with the adjustments required for that asset and transaction. For a straightforward purchase, start with the purchase record. A lot is simply a group of units acquired together. Different purchases can have different basis and holding periods.",
 "Start with what the investment cost you. The tax record calls the amount used in the gain calculation your cost basis. Purchase costs, fees and other required adjustments can affect it, so use the records. A tax lot is a group of units acquired together. Different purchases can have different costs and purchase dates."),
('5.1',
 "Let's use the lots in the course example.",
 "For the simplest example, suppose an investment sells for $20,000 and its supported basis is $16,000. Subtract the $16,000 from the $20,000: the gain is $4,000 before fees or other adjustments. The sale money is called proceeds. The proceeds, gain and tax bill are three different numbers.\n\nNow let's use the lots in the course example."),
('5.1',
 "For another simple example, selling an investment for $20,000 with $16,000 of supported basis produces a $4,000 gain before fees or adjustments. Treating the entire $20,000 as taxable gain would exaggerate the cost of using that money.\n\n", ""),
('5.2',
 "Then reconcile prior disposals with the filed tax record. The units already sold should not still appear as available lots. A loss carryforward needs support from the return and intervening activity, not merely an old screenshot showing a loss.",
 "Next, check past sales against the filed tax record. Units you already sold should not still appear as available to sell. If a tax loss was left over to use in a later year, that's a loss carryforward. Verify the amount still available from the returns and later activity; an old screenshot of a falling investment isn't enough."),
('5.3',
 "First, understand what a bracket means. With marginal ordinary-income brackets, moving some income into the next bracket does not generally move every earlier dollar into that higher rate. Think of filling layers rather than replacing the rate on the whole stack.",
 "A tax bracket is a range of income taxed at a given rate. Moving some income into the next ordinary-income bracket does not generally move all the earlier income to that higher rate.\n\nUse a made-up two-step tax to see why. Suppose the first $10,000 is taxed at 10%, and the next $1,000 at 20%. That's $1,000 of tax on the first part and $200 on the next, for $1,200 total. It isn't $2,200 from taxing the whole $11,000 at 20%. These are not actual tax brackets. They show why we ask what the next part costs."),
('5.4',
 "As a Traditional account grows, more money may eventually need to come out as taxable income. Let's compare whether using a lower-income year for a conversion would help—and what paying that tax now would cost.\n\nA Roth conversion is one way to address that. But “more money in Roth” is not enough reason to convert. We need to compare what the conversion costs now with what it changes later.",
 "Should you move some Traditional retirement money into Roth? A lower-income year may be a useful time to compare it. We'll look at the tax paid now and what each choice leaves later. More money in the Roth account is not enough to show that the household is better off."),
('5.4',
 "Choose an amount or range to compare, identify the account that pays the tax, and check what you expect to gain later. You may decide not to convert this year because the cost doesn't fit.",
 "Start with no added conversion as one choice. Then test an amount whose tax you could pay from money not already needed for bills or another commitment. Compare a smaller amount too. Read the cash used now and what remains later in each version.\n\nYou aren't looking for a number to copy. Choose the version whose benefit is worth its cost to you. If the extra tax would leave the early retirement years short, a smaller conversion or no conversion may fit better."),
('5.5',
 "Let's compare gain harvesting and loss harvesting. Both involve realizing something that was previously only a change in value, but they solve different problems.",
 "In these examples, harvesting means choosing to sell so a gain or loss becomes part of the tax record. Before the sale, it was a change in what the investment was worth. Gain harvesting and loss harvesting do different jobs; neither means the gain or loss itself is your tax bill."),
('6.1',
 "The course's starting illustration uses $96,000 of living expenses and $12,000 of healthcare: $108,000 before the other items we still need to reconcile. It also has $40,000 of gross income. The rough difference is $68,000.",
 "Start the example with $96,000 of living costs and $12,000 for healthcare. That adds up to $108,000. There is also $40,000 of income before tax. Subtract it, and the rough gap is $68,000. Keep that number in view while we add the costs not counted yet."),
('6.3',
 "Then compare the full cost, not just the monthly premium. Look at deductibles, copayments, coinsurance, network, prescriptions, and the out-of-pocket protection that applies. The out-of-pocket maximum may not cover every type of expense or out-of-network service.",
 "Then compare the full cost. The premium is what you pay to keep the coverage. The deductible is the amount you pay for services subject to it before the plan starts paying its share. A copayment is a set charge for care; coinsurance is a percentage of the covered cost you pay. Check which doctors and services the plan covers, called its network.\n\nRead the out-of-pocket limit too. It does not necessarily include premiums, services the plan excludes, or every out-of-network cost. Use the actual policy to see what remains your responsibility."),
('6.4',
 "An account order is useful as a starting rule. It saves you from inventing the paycheck every month. But an order that never considers the tax year can create an avoidable problem.",
 "An account order says which account you intend to use first and which follows. A blend uses more than one account for the same year's spending. Neither is best just because it has a name. Compare whether it supplies the cash you need, what tax it creates, and what money it leaves for later."),
('6.7',
 "An early funding failure is different from an unfavorable long-run terminal balance. A plan that would need a reduction the household cannot make should not be called comfortable simply because most paths work.",
 "Running short soon after you stop work is different from ending the plan with less money than you hoped. Find when the shortfall occurs and what the household would have to change. An adjustment you cannot actually make does not solve the problem."),
('6.7',
 "Assumption sensitivity deserves a separate comparison.",
 "Also test how much the answer depends on the assumed investment returns."),
('6.8',
 "Start with the spending policy you have chosen and the current, updated plan. A standing guardrail is a condition that calls for review. A proposed spending amount is the choice being considered for the coming year. Those are different things.",
 "Start with the updated plan and the spending rule you chose. A guardrail tells you when to review that rule. It might be a change in the portfolio's value or in the model's confidence result. The amount you decide to spend next year is a separate choice. First notice the reason to review; then work out what, if anything, to change."),
('10.2',
 "Use your own decisions and actual amounts, not a script you have memorized from the example.",
 "Use your own decisions and amounts, not a script memorized from the example. The reason matters: which need does the choice meet, and what do you give up to make it?"),
('10.2',
 "Their question can reveal a useful gap.",
 "Then change one fact in the conversation. Suppose work ends earlier, a new bill arrives, or someone no longer wants the current investment mix. Ask which part of the plan needs another look and what two choices you would compare. You don't have to decide immediately; you should know how to begin.\n\nTheir question can reveal a useful gap.")
]
