# Literal chapter plans: title, show/action, narration, verification, member finish.
CHAPTERS = {
'W05': [
('Understand the gain on one sale',
 'After 5.1, reveal the same hypothetical 0.2 BTC sale at $100,000 per coin. Proceeds stay $20,000; source allocated bases $11,600/$3,200/$10,400 produce gains $8,400/$16,800/$9,600. Identify what records establish each lot and what remains unknown.',
 '“The cash from the sale is the same in these rows. What changes is the cost of the units being sold. Subtract that supported cost to find the gain. The next calculation is the tax—not every dollar of the proceeds is gain, and the gain itself is not the tax bill.”\n\n“Before choosing a row, check whether those units can actually be identified and sold under the relevant rules. A smaller gain on a screen is useful only when the record supports it.”',
 'Verify current lot availability, quantity, basis, dates, fee treatment, account/wallet and timely identification. No dropdown equals legal compliance; no missing basis silently zero. Keep source quantities/categories unchanged and do not execute a sale.',
 'Explain proceeds, allocated basis and gain separately, with the actual prerequisite to use the preferred lots.'),
('Reconcile the purchase and transfer history',
 'After 5.2, use one accepted source file, one overlapping upload, one transfer and one unknown detail. Compare the account position before and after history. Use the generic no-fee 0.1 BTC example only as a separate illustration unless a reviewed capture extension supplies it.',
 '“Here is the purchase. These two records move that position from one location to another. We do not create a second purchase at the destination. Now compare the quantity before and after adding the evidence: the household should not own more Bitcoin just because we explained its history.”\n\n“This detail is still missing. We know the current position, but we cannot yet rely on its tax cost for a sale. Name the record needed instead of filling the gap with zero.”',
 'Verify Account detail and actual Upload account activity, certified native adapter or current supported guided mapping, duplicate receipt, missing basis/date/fee handling and transfer reconciliation. No universal source coverage or fabricated sale-and-repurchase workaround.',
 'The history needed for the decision reconciles, or the precise evidence gap remains visible without duplicate assets.'),
('Find the actual tax window',
 'After 5.3, open supported contextual Tax strategy and year detail. Show each person\'s employment and benefit dates, taxable-account sources and later required distributions. Identify one bounded income window and all other transactions using it.',
 '“This is where the income picture changes. Look at what funds spending during the gap and what taxable income it produces. Now we can ask a specific question: would using some Traditional money here improve the plan compared with waiting until later?”',
 'Verify jurisdiction, tax year, actual income types, withholding/estimated payments versus liability, account access and roadmap coverage. No assumed low-income Reed window before spouse dates and benefits are provided. No old-video bracket threshold or current default imported.',
 'A particular year or period and a transaction worth comparing, with any missing facts identified.'),
('Compare conversion, withdrawal and no change',
 'After 5.4, show the separate $30,000 Traditional plus $6,000 outside-tax-funding example, including opportunity cost and 20/30/10% later-tax variants. Then compare Current with one reviewed bounded conversion schedule and an accessible spending withdrawal where relevant, holding the funded life constant.',
 '“The converted amount goes into Roth; it does not also pay the bills. This other money pays the tax. Compare what remains in both versions at the same date, including the money we would have kept if we had not paid the conversion tax.”\n\n“Now look at the first affected year. Can the household still fund spending and the Reserve? Then read a later year. A larger Roth balance alone is not the decision—we want the after-tax benefit and the current cost together.”',
 'Verify actual incremental tax, outside tax source, lost investment opportunity, healthcare effects only where modeled, RMD exclusion, pro-rata basis, access clocks and planned/completed status. External calculation must be labeled. No fixed favorable Reed result or lifetime-tax-only ranking.',
 'A justified amount/range or decision not to convert, with separate spending and tax funding and specific review prerequisites.'),
('Prepare one harvesting action or deliberate pass',
 'After 5.5, review a real supported fictional candidate against the rest of the tax year. Contrast the separate $20,000/$16,000 gain and loss graphics. Prepare timely identification, replacement exposure, costs and current-rule checks before external execution.',
 '“This loss is not a refund of the same amount. Check what it can offset and what the replacement changes. For a gain, check the other income using the same favorable room. We are choosing a transaction that serves a purpose, not just reacting to the color of the return on screen.”',
 'Verify current asset/account/year rules, identification evidence, securities wash-sale interactions, relevant spouse/accounts, supported carryforwards and fees. Direct Bitcoin is not automatically a security fund; no permanent immediate-repurchase assurance. No proposed trade shown as completed.',
 'One reviewed proposal with prerequisites and deadline, or an explained decision to pass.'),
('Finish the professional and reporting packet',
 'Produce the supported FORM8949 TAX DATA CSV and inspect its actual coverage. Package only relevant records, transaction proposal, income context, uncertainty and the exact CPA question. Show post-transaction reconciliation as a labeled synthetic example only when reviewed.',
 '“This export supports preparation and review. It is not the filed return, and exporting successfully does not prove every record is complete. Here is the question we want answered, the evidence behind it, and the part still needing verification.”',
 'Verify exact export schema and values, missing records, safe handling and next-year lot continuity. No message sent, tax return filed or professional approval implied. Actual financial/tax records stay private.',
 'A usable handoff for a specific tax decision and a way to reconcile the executed result with the return.')
],
'W06': [
('Build the complete retirement cash need',
 'After 6.1, review the actual adopted lifestyle and healthcare spending, taxes, required debt and dated events, then expected income by person and date. Show the source rough $108,000 minus $40,000 = $68,000 separately from a completed net draw. The new hypothetical $126,000 total-cost/$86,000 gap extension is a teaching graphic only.',
 '“Start with what has to be paid, then the income already arriving. The rough subtraction helps us get oriented. This fuller view includes the costs it left out. Now identify exactly what the portfolio has to provide in this year.”\n\n“Move to the year when the next income source begins. The account balance did not suddenly become a different portfolio; the job we are asking it to do changed.”',
 'Verify gross/net units, tax gross-up, deductions already counted, income reliability, investment distribution treatment, person dates and same input/result receipt. No imaginary benefit, adoption of generic tax figures or double-counted withholding. Complete capture input decisions first.',
 'Explain one fully reconciled year and why another meaningful year needs a different draw.'),
('Fund the early years and compare benefit timing',
 'After 6.2, show both adults\' timelines. Alex\'s intended 52-to-59½ interval is 7.5 years; Morgan\'s own dates differ. Read actual income and usable accounts for every material interval and compare a supported benefit timing alternative.',
 '“Which source pays for this period before later income begins? The total assets are not enough of an answer. Point to the account and the rule that makes it usable. If we wait for the benefit, show the extra funding needed before it starts as well as the later income it provides.”',
 'Verify individual SSA/pension estimates, earnings record, dollar convention and survivor/spousal effects where supported. Early access requires exact account/separation/Roth ordering/457/SEPP conditions. No universal claiming age or assumption all retirement dollars unlock together. Unmodeled benefits remain separately reviewed.',
 'Every early interval has a supportable source or a clearly identified funding/access prerequisite.'),
('Put coverage and healthcare costs on the timeline',
 'After 6.3, compare relevant pre-Medicare options with actual private quotes or clearly invented teaching inputs. Show the $15,000 versus $16,000 ordinary-year illustration separately, then real difficult-year limits/exclusions and each person\'s transition.',
 '“The lower premium is only one part of what we pay. Add the other expected costs, then check what a difficult year could require. Who covers that amount, and what happens to the plan if this tax decision changes the net coverage cost?”',
 'Verify provider networks/prescriptions, dates, exclusions, eligibility and enrollment, Marketplace income, Medicare lookback and HSA coordination. Noninsurance retains its actual unfunded-cost risk. No personal medical story, invented quote or unsupported subsidy engine; outside analyses labeled.',
 'A funded coverage path and specific required confirmations before leaving current coverage.'),
('Choose account funding and asset sales',
 'After 6.4, compare the current account order with a deliberate blend on the same spending and market assumptions. Show which asset is sold inside the account, required distributions, taxes, spending cash and any separate conversion.',
 '“First choose the account supplying the withdrawal. Then read what was sold inside it. The gross withdrawal and the amount available for bills may differ. Now compare the early year and a later distribution year so we can see why a blend might help—or why the simpler order is already sufficient.”',
 'Verify actual withdrawal and asset-priority controls, lot evidence, access, cash gross-up, RMD compliance, dividend treatment and same-state results. No automatic optimal blend or never-sell-Bitcoin promise. Save only the deliberately adopted fictional choice.',
 'Explain the next withdrawal, tax funding and asset sale and the relevant later-year consequence.'),
('Use the Reserve through a weak sequence',
 'After 6.5, show the exact separate sequence graphic: $1m, $50k beginning-year withdrawals, −20/+25 => $887,500, reverse => $910,000. Then read actual retirement cash target, source, use/refill rule and a weak year near the floor.',
 '“The same two returns did not produce the same retirement outcome because withdrawals occurred along the way. Here is the cash already available to support spending. If we use it during the decline, how long does it last, and what is the response before it no longer covers the bills?”',
 'Verify actual reserve/refill implementation, finite floor, eligible funds, transfer counting and taxes. Cash remains inside the portfolio; no unsupported automatic pause/refill feature or video fair-value price trigger. Do not claim a reserve eliminates sequence risk.',
 'A finite use/refill policy with an actual funding response and clearly retained uncertainty.'),
('Compare sale, another source and borrowing',
 'After 6.6, compare the same net spending and date across sales, another available source and an actual supported borrowing policy. Read strategy, assumptions receipt, rate path, capitalized/paid interest, collateral and repayment. Generic $20k at 10% is a separate graphic, not a loan quote.',
 '“Keeping more Bitcoin initially is one possible benefit. Follow the obligation as well. What funds the interest, what remains owed after a weak year, and how does the loan end? Compare that with the sale\'s tax and the lender exposure it avoids.”',
 'Verify actual D63-supported policy and any Hybrid Sell within your tax limit, then borrow semantics. Default 50% initial LTV is not a recommendation. No new actual Reed loan, fabricated liquidation probability, provider assurance, estate guarantee or unsupported contract representation.',
 'A considered funding policy with its weak-period and exit trade-off explained.'),
('Test a decision rather than chase a score',
 'After 6.7, compare Current with one realistic spending, work-date or funding change. Read actual percentage, count, horizon and freshness, then the year that explains the difference. Keep changed and inherited assumptions visible.',
 '“What did we change, what did it affect, and what did the household give up? If this result requires spending cuts the family would not make, a higher percentage has not finished the decision. Choose the version whose trade-off you understand.”',
 'Verify actual same-state result, supported scenario behavior and current methodology. No hidden return/volatility edits, forced target score, fabricated Reed outcome or assumption all risks are modeled. Below-standard intended timing is an acceptable truthful demonstration.',
 'An adopted preference or specific gap, with realistic adjustment capacity and unmodeled risks understood.'),
('Finish the annual spending and refill decision',
 'After 6.8, read standing guardrails separately from the current annual proposal. Compare next-year spending, inflation and change limit alongside the tax/withdrawal/refill effect. Use the separate $100k-to-$95k example only to explain the practical spending change.',
 '“This portfolio level calls for a review. This other amount is the spending we are considering. What would actually change in the household budget? Then follow the money and decide whether the proposal, a different amount, or another response fits.”\n\n“Finish with the next-year paycheck in ordinary language: what we will spend, what income arrives, which accounts provide the gap, and when we review it again.”',
 'Portfolio-dollar thresholds require approved inverse calculation and denominator. Verify actual policy/annual window, cap, inflation, preview/adoption and save/reload; repeated saves cannot evade a cap. Do not substitute old slide percentages or label a confidence value as a portfolio dollar. Urgent debt/coverage events retain separate action rules.',
 'The chosen spending, income, withdrawals, Reserve, borrowing policy and review date describe one operating plan.')
]
}
FINISH = {
'W05':'The member understands the tax consequences of the proposed action, has the evidence needed to compare it, and can hand a specific question to the appropriate professional. A record, modeled result, reviewed proposal, executed transaction and filed return remain different states.',
'W06':'The household can explain the actual retirement paycheck across its important dates and a difficult period. The annual spending and Reserve decisions fit the same funding. All result values come from the approved saved example; unsupported financial or contract behavior remains explicitly unverified, not staged.'
}
SETUP = {
'W05':'Use the unchanged source lot example plus reviewed synthetic acquisition/transfer/overlap records and a separate fictional tax-year extension. No real client tax records or transactions. The new conversion opportunity-cost and gain/loss graphics are labeled educational assumptions, not engine outputs. Preserve supported account-activity, identification and tax-data export boundaries.',
'W06':'Complete the fictional capture extension before running the approved engine: as-of and each person\'s timeline, spending adoption, income/benefits, coverage, tax treatment, debt schedules, account access and return assumptions. Retain the original fixture untouched. There is no predetermined success percentage or retirement age. Individual chapter recordings need the actual input/result identity and approved behavior.'
}
