# Literal chapter plans: title, show/action, narration, verification, member finish.
CHAPTERS = {
'D07': [
('Identify the isolated practice setup',
 'Verify manufacturer, model, firmware, wallet software, backup standard and official current procedure. Show only the non-secret equipment and stated purpose. Use an independently reviewed test plan and a separately authorized trivial amount.',
 '“This is a practice setup, separate from the wallet holding the family\'s savings. We are learning the process and checking what this particular recovery would prove. Start with the official instructions for this exact device and backup format.”',
 'Authenticity and procedure must match the actual equipment. Unexpected or prewritten recovery material is a stop. No funded household wallet or universal reset sequence. Receipt records official URL/date and reviewer.',
 'The safe scope and exact procedure are known before setup.'),
('Create the test wallet off camera where secrets appear',
 'Create a fresh isolated wallet only within the reviewed process. Stop screen and device capture during generation and recording of every secret; do not rely solely on later blurring.',
 '“The recovery information is private. We are not recording it or putting it in a course file. I will show the non-secret result of the setup, not the material that could let someone control the wallet.”',
 'No usable seed, private key, passphrase or sensitive recovery configuration enters distributable footage or intermediate recordings. Never use a pre-populated practice secret copied from a tutorial.',
 'The wallet is established with secret material confined to the approved offline process.'),
('Explain the recovery requirements',
 'Use labels, not actual values, to distinguish PIN, backup and any passphrase. If multisig or another standard is involved, use its separately reviewed complete requirements instead of pretending a word list alone suffices.',
 '“The PIN protects access to the device. The backup restores the corresponding keys. A passphrase can select a different wallet, so the exact passphrase is part of that recovery. These pieces do different jobs.”',
 'Verify actual backup standard and compatible recovery method. Valid words are not proof of the intended passphrase wallet; no universal secret split or assumption all devices use the same word count.',
 'The operator knows which information the actual setup requires and what each item does.'),
('Receive a small authorized test amount',
 'Verify a receive destination through the official trusted device process. Conduct only the explicitly approved small test transfer and wait for the appropriate confirmation. Keep unnecessary identifiers out of the camera frame.',
 '“Check the destination on the trusted device, not just on the computer. This small amount gives the recovery test something real to verify without putting meaningful savings into the experiment.”',
 'Correct network, destination and amount; no live household transfer authorization implied. Record only non-secret expected-wallet evidence and actual test confirmation.',
 'The intended practice wallet and its test receipt are identified.'),
('Check the backup before any destructive step',
 'Use the supported non-destructive backup check or safely prepared compatible spare-device process first. Keep the working source intact. Stop when any check fails.',
 '“Before removing anything, check the recovery material through the official process. If this check fails, the next step is to understand why—not wipe the only working access and hope the recovery succeeds.”',
 'Exact manufacturer procedure, genuine app, backup validity and passphrase/configuration requirements verified. No secret disclosure to support. Failure or mismatch means no reset, no new meaningful funds and no success status.',
 'The next step is justified by actual safe evidence, or the test stops with a controlled recovery plan.'),
('Recover the intended wallet within the reviewed test',
 'Only if explicitly included in the approved isolated procedure, perform the test reset/restore or use a compatible spare. Keep all secret-entry capture off. Verify a known non-secret wallet identifier/address and the expected test funds.',
 '“We are checking for the intended wallet. Opening a valid empty wallet is not enough. Compare the expected identifier and the small test position before calling this a successful recovery.”',
 'No funded primary device wiped as a first test. Exact device, format, passphrase and configuration supported. Mismatch aborts the procedure; do not troubleshoot by moving meaningful funds.',
 'Actual recovery of this intended practice wallet is proven or accurately marked failed/pending.'),
('Verify controlled spending and the fee',
 'Review a separately authorized small outbound practice transaction through the trusted device process. Read the actual fee and destination; no universal fee or dust threshold.',
 '“Now confirm that this recovered setup can authorize the intended small transaction. Read the destination, amount and fee before confirming. A recovered balance and a verified spending operation tell us different parts of the result.”',
 'Explicit transaction authorization and current wallet procedure required. No publication of keys, private metadata or unnecessary addresses. Confirmation must actually exist before described as complete.',
 'The practice operation is verified under the exact test scope.'),
('Record what was proved and what was not',
 'Complete non-secret receipt: setup, method, date, actual outcome and limitations. Review all distributable footage and source recordings for secrets before release. Send only scoped status to W07.',
 '“This proves the process for this practice wallet. It does not prove the backup of a different funded wallet. That setup needs its own appropriate safe verification. Record the difference so the family does not rely on a test that never covered its actual holdings.”',
 'Independent security review, secret-free export and exact actual-wallet status required. No blanket recovery approval, implied manufacturer endorsement or app-plan export treated as a wallet backup.',
 'A truthful practice-test receipt and a separate status for each actual holding.')
],
'W07': [
('Choose custody for the household job',
 'After 7.1, use the existing Family Custody Map and fictional example. Review direct Bitcoin, professionally held Bitcoin and brokerage-fund exposure separately, with owner, job, desired control, responsibility and retained dependency.',
 '“What problem is this arrangement solving? This portion provides direct control; this other process provides support with different dependence. Name both the benefit and what the household still has to manage. More methods are useful only when they address a real gap.”',
 'Verify actual supported Protect fields and current owner/account facts. No invented provider rights, insurance, wealth-tier recommendation or independent recovery claim. Dedicated account and fund rules remain distinct.',
 'An intentional direction for every meaningful holding and a specific first protection action.'),
('Record actual recovery evidence',
 'After 7.2 and D07, read the actual scoped receipt. Keep practice-wallet proof separate from verification relevant to a funded holding. Record dates/method/status only when supported.',
 '“Which setup did this test cover? If it was the practice wallet, this funded wallet still needs its own check. We would rather keep one task visibly open than tell the family a backup was verified when it was not.”',
 'No checking Tested by default, no purchase-of-hardware equals recovery, no secrets or sensitive descriptor/xpub data in the ordinary record. Device-specific work stays in the reviewed procedure.',
 'Recovery statuses and next actions match the actual evidence.'),
('Fix one important account or shared-dependency gap',
 'After 7.3, identify a shared recovery email, operator, provider or location. Choose one actual account-hardening action. Demonstrate only on an authorized example account and record the external confirmation or pending task.',
 '“These logins share the same recovery route. Adding another account would not solve that failure. Let\'s fix the route we found, test the backup access, and then record what changed.”',
 'Verify actual passkey/security-key/allowlist features, backup recovery, provider terms and confirmation. No passwords, recovery codes, exact locations or live client credentials filmed. Hardening does not certify provider solvency.',
 'One meaningful improvement with a named owner and evidence, plus remaining dependencies.'),
('Finish the family starting map',
 'After 7.4, complete the non-secret first contact, lawful starting route, review triggers and outside task for each arrangement. Use a consented operator-unavailable tabletop and revise a specific unclear instruction.',
 '“Show me where you would begin without asking the unavailable person. This map directs you to the legitimate process; it does not contain the keys. A financial-plan backup restores plan data, not access to the Bitcoin wallet.”',
 'Verify actual read/export/restore scope separately. No exact secret storage, complete signing route or fabricated listener outcome. Qualified legal authority and operational help remain separate.',
 'A usable dated map and truthful protection status with the relevant family starting process.')
],
'W08': [
('Connect people, documents and beneficiaries',
 'After 8.1, fill the existing role/document inventory with primary and backup willingness, incapacity and death roles, document execution status, ownership and account beneficiaries. Use no invented Reed legal choices.',
 '“This person is intended to help. Now identify the document or process that gives the relevant authority. A nomination, an executed document and an actual appointment are different statuses. If the beneficiary record conflicts with the intention, that is the correction to take to the attorney or provider.”',
 'Supported non-secret fields only. State-specific authority and document execution require legal review; a checkbox is not a legal instrument. No auto-created guardian/trust or assumed beneficiary outcome.',
 'A clear role and document gap list with the responsible outside action.'),
('Connect authority to practical access',
 'After 8.2, trace direct custody and an institutional account from ownership to authorized role, provider/technical support and immediate cash needs. Test incapacity separately from death.',
 '“Knowing how to operate the wallet is not the same as being entitled to use it. For this account, who has authority and who provides the technical or provider process? Both need to connect before the family can rely on it.”',
 'Verify actual legal/provider requirements and available cash. Trusted contact is not withdrawal authority; no owner-login impersonation, universal seed/passphrase split or presumed immediate asset access.',
 'Each important asset has a legitimate starting route and precise unresolved prerequisites.'),
('Write and rehearse the first-page handoff',
 'After 8.3, complete the existing Heir Letter and Executor Packet using the example paragraph as new illustrative language, not legal advice. Tie to the Family Custody Map. Ask a consented nontechnical person to explain the first step and backup contact.',
 '“The letter gets the reader started. The packet supports the follow-up. Let\'s read the first page without my explanation: whom would you contact, how would you verify the contact, and what should not be rushed? Fix the confusing sentence before adding another page.”',
 'Actual finding/opening and teach-back required before success status. Keep keys, secrets and detailed protected storage out. No unperformed delivery, attorney review or fictional client test asserted.',
 'Findable, understandable first instructions with actual rehearsal gaps corrected.'),
('Verify the communication backstop',
 'Use a harmless agreed recipient and test message only after the actual release/account mode demonstrates any check-in or delayed-notification feature. Read waiting period, cancellation, false-alarm handling, delivery and access. Record external placement when needed.',
 '“A missed check-in and a message arriving are separate events. This test sends directions, not keys. Check that the recipient can actually open the message and has another legitimate way to begin if this service is unavailable.”',
 'No assumed 90-day default, delivery guarantee, automatic key release, real death notice or unsolicited sensitive communication. An unavailable promised capability is reported and held, not quietly simulated or relabeled shipped.',
 'A tested communication route and fallback, or an explicit outside task without false delivery approval.'),
('Complete the risk and insurance decision',
 'After 8.4, use the existing insurance audit. Review actual coverage evidence or labeled hypothetical mechanics against one material loss, then check all other relevant risks. Separate benefit, waiting period, exclusions, premium, beneficiary and retained risk.',
 '“What loss is the household trying to cover? Compare that need with what this policy actually provides. We are not buying one of every product. We want the gap, the resources covering it and the professional question that remains.”',
 'No invented insurance-analysis app feature, coverage quote or insurability. Actual policy/qualified review and replacement effective date precede cancellation of needed protection. Contracts stay private.',
 'Each material risk is covered, deliberately retained or assigned a precise reviewed action, with plan costs updated.')
],
'W09': [
('Complete a quiet monthly review',
 'After 9.1, review actual account changes, current cash flow/Reserve, upcoming events and result freshness. Show an honestly quiet month and finish with no invented task. Timing may be measured but not promised universally.',
 '“We are checking what changed. These facts are current, the expected transfers are accounted for, and there is no new decision to make. A quiet month can end here.”',
 'Verify Home/needs-attention and actual source state. No mandatory number of actions, five-minute guarantee, repeated forced allocation change or lender monitoring reduced to monthly cadence.',
 'The member can repeat the factual check and knows when to stop.'),
('Resolve one meaningful exception',
 'Use a synthetic discrepancy, such as a transfer counted on both sides without the source reduction or a contribution left uninvested. Inspect the actual cause and supported resolution. Compare resolved, deferred, uncertain and snoozed states.',
 '“The number is different from what we expected. Find which record explains it before adding another entry. A postponed question is still open. Once the fact is corrected, check the result it actually changes.”',
 'Verify contextual action and receipt; no fabricated balancing purchase/cash, silent deletion of evidence or double import. Protect holdings/history distinctions and current result identity.',
 'A supported correction or precise open task with its consequence understood.'),
('Complete the annual system review',
 'After 9.2, use the prior dated plan and Annual Plan Refresh. Review spending/Reserve, Allocation, Debt, Tax, Custody, and family/insurance decisions within their actual screen owners. Inspect real debt-payoff and Reserve-completion milestones before routing new money.',
 '“Start with the choices already made and ask what changed. This payment ended, but before assigning it again, check the current cash needs and contribution plan. We are updating the system, not retaking the course or searching for a new strategy every year.”',
 'Actual supported scenario and annual-spending window only. Tax, security and collateral deadlines retain separate timing. No destructive funded-wallet test, automatic rebalance or assertion old beneficiary documents remain legally sufficient.',
 'One coherent annual record of reviewed choices, adopted changes and dated outside actions.'),
('Handle a real change and a proposed response separately',
 'After 9.3, adopt one reviewed fictional income/event change at the correct date, then compare a strategy response. Read essential needs first, and the resulting cash flow and Plan update state. Reconcile a future event once actual.',
 '“This income changed in real life. Update that fact first. This contribution change is our proposed response. Keeping them separate lets us see whether the response solves the cash problem rather than hide it.”',
 'Verify actual save/update and freshness, event lifecycle and Current/Preview. No invented Recalculate control, assumed exact date or compensating return override. Immediate contract obligations do not wait for app support.',
 'Current reflects the fact and the response is an explicit choice.'),
('Keep the next review usable',
 'Save a dated readable summary, Annual Plan Refresh and action list through supported paths. Identify the separate protected backup and verified restoration scope; include monthly/annual and specific urgent review triggers.',
 '“Next year starts from this record: what we chose, why, and what remains to be done. The readable summary helps us review the decisions. The backup has a different job, and its restore process needs its own verification.”',
 'Actual export, save/reload and restore capability verified separately. A written reminder is not a calendar event or a completed outside action. No sensitive file sent or old version left as the current instruction.',
 'A maintained dated plan with a repeatable review path and honest implementation status.')
],
'W10': [
('Read one coherent saved plan',
 'With 10.1, open the actual report and Household Plan Summary. Follow life goal, current position, same-phase cash flow/contributions, whole portfolio, intended/calculated timing, assumptions and limitations. Position/Trajectory/Risk/Actions is a teaching order, not a promise of fixed interface chapters.',
 '“Every statement here needs to describe the same plan. Start with the life it is funding, then trace the important numbers back to their source. A result is useful when you can explain what supports it and what still needs to change.”',
 'Verify actual report and exact source/result identity. No original/reduced/post-card state mixing, landing-page placeholder, assumed approval or unverified model outcome.',
 'The summary and current report explain the same facts, intentions and calculated result.'),
('Follow the important funding years',
 'Inspect the first retirement year, benefit start, a significant event and a later tax-sensitive year. Read income, complete spending, taxes, withdrawals, source accounts, debt and ending resources from one real reviewed input set.',
 '“These are the years where the funding changes. Show which account pays this need, what tax or payment goes with it, and what is left for the years afterward. That is how we check the headline against the life it is supposed to fund.”',
 'Real output only. Missing source attribution or unsupported risk remains visible; no invented ideal plan, account access or future dividend/benefit. Blocking uncertainty is not relabeled a finished decision.',
 'Explain critical transitions and the most important sensitivity or remaining gap.'),
('Have the listener explain the plan back',
 'With 10.2, use an explicitly consented nontechnical listener. Present the short household explanation, then ask for next-period funding, the next action and the safe family starting process. Revise the actual point of confusion.',
 '“You do not need every technical detail. Tell me where the next spending money comes from and which action happens first. If that is unclear, we need to improve the explanation—not ask you to memorize more terminology.”',
 'Record an actual rehearsal, not claimed member validation from a script or test. No private client footage, secrets or staged perfect comprehension.',
 'The listener can use the explanation, or the observed gap is corrected and retested.'),
('Prepare the specific professional handoffs',
 'Prepare only the relevant CPA, attorney, coverage or lending packet. Include the proposed decision, supporting evidence, exact unresolved question and deadline. Review and minimize any supported export before sharing.',
 '“Here is the decision, the evidence behind it and the question the professional needs to answer. Preparing this packet does not mean advice has been received. Keep that status clear before taking the dependent action.”',
 'Actual export coverage/privacy and recipient authority checked. No automatic message, appointment, filing or professional approval inferred. No general full-backup sharing or sensitive custody details.',
 'Each consequential open issue has a focused handoff and the right prerequisite.'),
('Save the operating plan and implementation record',
 'Save dated plan, Household Plan Summary, outside actions, review schedule and appropriate verified backup. Use the Annual Plan Refresh as the next-year starting point. Distinguish current and future conditional tasks and deliberately retire superseded instructions.',
 '“This is the plan we intend to follow. These actions are completed, these still need doing, and these begin only after their condition occurs. The next review starts with these reasons intact, not with a blank page.”',
 'Verify actual save/reload/export/restore scope and remaining approvals. No fixed three-task maximum or video-watched equals completed plan. Student release and actual execution are separate authorizations.',
 'A explainable, dated plan with practical next actions and a repeatable maintenance process.')
]
}
SETUP = {
'D07':'No hardware procedure is approved by this manuscript. Before filming, record exact manufacturer/model, firmware, wallet software, backup standard, official procedure URL/date, authorized trivial amount and independent security review. Preserve all working access until the reviewed procedure permits otherwise. Secrets remain off camera and out of intermediate recordings.',
'W07':'Use existing member deliverables and the unchanged fictional account inventory. Protect records non-secret facts and status, not recovery keys or an untested assurance. Architecture decisions, actual tests and user competence must be evidenced separately.',
'W08':'Use the existing Heir Letter, Executor Packet, Family Custody Map and insurance audit. These organize a household decision; they are not legal instruments or professional approvals. Actual people, communications and account/legal changes require consent and appropriate verification.',
'W09':'Use the same saved household and existing Annual Plan Refresh. Monthly facts, annual strategy and urgent obligations have different purposes and cadences. An unchanged plan can be the proper reviewed outcome.',
'W10':'This capstone requires one actual engine-backed saved fictional plan and its matching documents. Do not combine convenient numbers from different examples. A listener rehearsal, outside implementation, legal review and capture receipt must actually happen before recorded as successful.'
}
FINISH = {
'D07':'An actual safe test of the intended practice wallet is documented with its limits. The actual household wallet remains separately verified or pending. No usable secret material or sensitive recovery metadata appears in the distributable footage; without hardware evidence, filming approval remains open.',
'W07':'Custody direction, account security, recovery evidence and the family starting map describe the same holdings with their retained risks. All status claims are scoped to actual evidence.',
'W08':'The intended person can find a legitimate starting process and the legal, operational and insurance questions are connected to their specific outside actions. Letter creation alone does not prove authority, delivery, recovery or coverage.',
'W09':'An ordinary month, a material exception and the full annual loop can be followed without unnecessary strategy changes. The latest plan and action record form a usable starting point for the next review.',
'W10':'The member can explain the current position, whole portfolio, new-money plan, retirement funding, retained risks, family process and next actions. Any blocking prerequisite remains visible. Written preparation is complete; learner success and app/device execution require real evidence.'
}
