# Literal chapter plans. Fields: title, show/action, spoken narration, verification, member finish.
CHAPTERS = {
'W01': [
('Find the first task',
 'After 1.1, open the actual starting state. Orient only the next task and its owning screen. Use the existing mortgage, expected college and possible renovation to distinguish facts, events and scenarios; keep assumptions with the saved starting plan.',
 '“We are starting with what is true today. This is the next record to complete. The mortgage already exists; the college support is expected; the renovation is still a question. Keeping those separate gives us a starting point we can return to after a comparison.”',
 'Verify Home, Plan, Cash Flow, Protect and the actual Build & improve entry and owning editor. The guide must not create a second fact store. Minimum inputs and any preliminary estimate must match the approved build; no invented success percentage.',
 'Find the next task and classify a current fact, expected change and what-if.'),
('Review accounts and holdings',
 'After 1.2, demonstrate one cash account, one investment account and direct Bitcoin. Use source checking $18,000, Alex Roth $145,000 and direct location 3.4 BTC at the frozen teaching price. Review existing records rather than duplicate accounts. Introduce the other accounts only as needed.',
 '“This is who owns the account and how it is treated. These investments explain the balance inside it. Before moving on, compare the total with the statement. We want one account and one explanation of what it owns—not two copies of the money.”',
 'Verify entry, classification, owner, tax treatment, as-of and price handling and save/reload. Fixture categories are not exact fund identities. HSA/education holdings and provisional education owner require reviewed capture treatment. Do not infer native coins from fund exposure.',
 'One record per account with supported owner, type, total and known holdings.'),
('Read connected-source coverage',
 'Use an authorized synthetic connected-source example. Read actual coverage for balances, holdings, activity and purchase details, including an incomplete case.',
 '“A connection can supply part of the picture. This source has provided the balance. Now check whether it also supplied the investments and history. If it did not identify the holdings, that money is not automatically cash. We know exactly which part still needs attention.”',
 'Verify actual capability receipt and freshness; do not infer Fully synced from the institution name. No real client credentials, provider connection or paid refresh is authorized by this writing.',
 'Explain what arrived and the supported next completion step.'),
('Explain a balance-only investment account',
 'For the same account total, demonstrate the accepted multi-position entry or mutually exclusive Estimated mix. Use the source Roth category amounts $116,000 spot-fund exposure and $29,000 stocks only as categories unless a reviewed security extension supplies exact holdings. Confirm genuine cash independently and leave unresolved remainder unknown.',
 '“We know the total. Now we are explaining what is inside it. These amounts should add up to the same account value, counted once. Money we have not identified is a question to resolve; calling the remainder cash would answer that question without evidence.”',
 'Verify actual Holdings needed state, Add investments action, Shares/Current value or Estimated mix path, lookup, classifications, unknown basis/date, discrepancy handling, atomic save receipt and reload. No single-security shortcut, fake purchase or invented ticker. Hold this chapter when the complete accepted path is unavailable.',
 'Explain the saved composition mode, total, confirmed cash and remaining unknowns.'),
('Attach history without another holding',
 'Use a reviewed fictional purchase-and-transfer chain, plus a deliberate overlap. Compare the current quantity before and after accepted historical evidence. Keep unknowns visible.',
 '“This tells us how the existing position got here. We are not buying it again. Follow the transfer from the old location to the new one, then check that adding the history has not increased what the household owns.”',
 'Verify certified import/mapping, actual transfer and deduplication behavior, retained basis and current-position reconciliation. No sale/repurchase substitute for unsupported transfers. Missing history does not block unrelated cash-flow work.',
 'History explains the current position without duplicate assets or invented basis.'),
('Enter the starting monthly picture',
 'After 1.3, review income meaning, current living costs, required debts and employee contribution. Show the original source bridge as a separate graphic where needed: $19,416.67 gross, $4,000 tax provision, $10,800 living, $3,341.67 required debt, $1,275 before employee, $775 employee, $500 remaining; $387.50 employer separate.',
 '“Follow what has already come out. Alex is already contributing through work. The $500 is what remains after that contribution, not the total being saved. If the result differs from the bank records, we will investigate the difference in Cash Flow before assigning another transfer.”',
 'Verify gross/net fields, business operating costs and equipment payment treatment, payroll election, required-debt source, provision versus calculated liability and result update. Round only after full-precision calculation. Do not force the app to $500 with an unexplained override or activate reduced spending early.',
 'Explain the initial income, costs and commitments and identify a real mismatch for W02.'),
('State the retirement question',
 'Record preferred Alex age 52 and each person\'s separate intended work change. Use reviewed capture dates, adopted spending, healthcare, benefits and horizon; no exact birth date or benefit quote is supplied by the fixture.',
 '“This is when Alex would like work to become optional. It is a question for the plan, not a result. Now check what spending and income describe that life, and which estimates still need work.”',
 'Verify owners, age/date conventions, income end/start, today\'s/future-dollar units, horizon and saved readback. The source $96,000/$12,000/$40,000 retirement illustration is not automatically adopted. Missing material inputs prevent claiming a complete valid result.',
 'The intended life is recorded, with precise remaining input questions.'),
('Read and test the assumptions',
 'After 1.4, read the actual chosen path in an early and later year. Compare one less-favorable growth assumption while keeping spending, contributions and work choices fixed; return to Current without adoption.',
 '“This is the assumption we changed. These household choices stayed the same. Now look at the year where funding differs. We want to know which decision depends on this belief, not just whether the headline moves.”',
 'Verify preset path, units, supported custom periods and overrides, classifications, Current/Preview identity, freshness, cancel/save/reload. No old preset rates, return guarantee or unsupported security simplification.',
 'Explain the model and the consequence of one controlled sensitivity.'),
('Read the first complete result',
 'After 1.5, use the actual approved input/result receipt. Read intended and calculated dates, percentage, exact count and horizon, then inspect one meaningful funding year. Show a below-standard date honestly when it occurs.',
 '“This is the date they chose, and this is what this calculation supports. Let\'s open the first year after work changes. What income arrives, what needs paying, and which account supplies the remainder? That is where we find the next useful comparison.”',
 'Verify preliminary-to-full transition, actual standard and advanced settings, input completeness, freshness and save/reload. The 79% illustration remains outside the interface. Do not assert 800/1,000 as the actual default until verified. No preselected winning Reed result.',
 'Explain the actual starting answer and one next accuracy check or realistic choice.'),
('Ask about the populated plan',
 'After 0.2, ask one question about the actual number already shown. Trace the real response back to the relevant rows. Demonstrate market-report and outside-AI-summary inserts only after proving availability and content.',
 '“We have one question and the numbers behind it. Check whether the explanation uses the same date and inputs. If it does not, stop there rather than changing the plan to agree with it. Once the number is clear, choose the next check or comparison.”',
 'Verify Ask context/permissions, source links, no implicit adoption, report dates/sources and actual summary-export schema/privacy. A restoration backup is not an AI summary. No staged AI response, assumed anonymization or silent omission of a promised unavailable feature.',
 'Explain one answer independently and handle any sharing or next action deliberately.')
],
'W04': [
('Read the current whole portfolio',
 'After 4.1, show one account then the combined general subset: $1,307,000, native Bitcoin value $410,000, spot-fund $318,000, stocks $504,000 and cash/Treasury category $75,000. Native quantity remains 4.1 BTC. Home/HSA/education stay on the balance sheet but outside this target subset.',
 '“The wallet is only part of the Bitcoin exposure. These funds add another part, while remaining securities in their accounts. Now read the other holdings. Which job is each doing, and is there one mismatch we should solve before buying anything else?”',
 'Verify eligible denominator and source classifications without adjusting balances to force a percentage. Current-value/Estimated mix is distinct from known security positions. Current purchases and account ownership need evidence.',
 'Explain current exposure and the non-Bitcoin holdings with the portfolio scope clear.'),
('Choose Bitcoin\'s intended role',
 'After 4.2, use the original four-path slide and indicative ranges as orientation. Record the household\'s preferred role or starting range, not a final target or an automatic app suitability result.',
 '“Which description fits why you own Bitcoin? You may already be comfortable with the current position. Write that starting intention down. We will decide what the other money needs to provide before treating the percentage as a finished portfolio.”',
 'No repeated drawdown arithmetic, no target save here, no mandatory bands or custody/wealth ladder. The role may be documented in the existing worksheet when there is no corresponding app field.',
 'State the intended role and the question the remaining holdings must answer.'),
('Build the non-Bitcoin portion and combine the target',
 'After 4.3, use a separate $1 million teaching graphic. $500,000 BTC preference; prior $60,000 Reserve plus distinct $40,000 purchase produce $100,000 cash; remaining $400,000 long-runway stocks because this hypothetical household wants broad business ownership rather than individual-stock concentration. Compare cash arrangements, stock coverage/cost, and a relevant bond alternative by job—not by current yield or product recommendation.',
 '“First we found the dollars needed for actual commitments. That produced the cash amount. Then we chose what the remaining long-term money should provide. The stock allocation is a choice to own businesses alongside Bitcoin, not an automatic destination for every spare dollar.”\n\n“Now add two separate $50,000 retirement payments that this household wants available in cash. Keeping Bitcoin unchanged leaves less for stocks. Their conviction stayed the same; the spending job changed. Which version better fits the life they intend, and what growth exposure are they giving up?”',
 'Show first 50/40/10 then 50/30/20; all amounts and preferences are explicitly invented instructional assumptions, not Reed outputs or recommendations. The earlier $500k weighting-only example is superseded in this recording. Return to actual Reed jobs and supported sources before any target save. No per-bucket editor, second ledger, automatic recommendation, verified securities or cash eligibility inferred. Check first funding date/access and costs; an unavailable app feature remains held.',
 'Explain the whole chosen mix, why each amount and investment type fits, a meaningful alternative and the first payment source.'),
('Fit current contributions and future milestones',
 'After 4.4, use the actual reduced-spending state: $2,475 before employee − $775 = $1,700; $500 Reserve plus $1,200 extra card use it all. Read employer $387.50 separately. Show the conditional card-payment release $1,605 and later Reserve-completion milestone, not current additional money.',
 '“These are the decisions already made. They fit in one available amount, so there is no additional transfer to add now. We can prepare where the payment goes after payoff, but first the payment has to end and the cash flow has to be checked again.”',
 'Verify actual contribution and extra-debt owners, current/future conditions, match formula and vesting, supported date behavior, no automatic bank routing and save/readback. Required debt is already deducted. A tax-election change later must reconcile this budget.',
 'Every current contribution is funded once and later contributions have real start conditions.'),
('Select the relevant accounts',
 'After 4.5, show the funding job first, then only relevant account alternatives. Compare actual access, eligibility, remaining room, menu, fees and tax treatment. Include HSA/529/business arrangements only when purpose and eligibility apply.',
 '“Which account can do this job? If we need the money in the early years, verify the access route. For later money, compare the tax treatment and menu. This workplace plan can hold part of the portfolio even if another account is the better place for Bitcoin.”',
 'Verify per-person access and current rule/plan evidence. HSA/education are not unrestricted bridge money; self-directed retirement custody is not a personal account. Fictional workplace menu is not a real provider promise. New account opening stays an outside task.',
 'Choose the receiving account or a precise prerequisite, rather than copying the whole example account list.'),
('Compare the tax election fairly',
 'After 4.6, show the separate $1,000 pretax example: $1,000 Traditional versus $800 Roth at 20%, both double, after-tax Traditional $1,600/$1,400/$1,800 at 20/30/10%. Then compare the actual reviewed payroll choices on a clearly specified equal-contribution or equal-household-cost basis.',
 '“Traditional has more invested initially because the income tax has not been paid yet. Finish the comparison by taking withdrawal tax out. Now check the current paycheck: if this election leaves less cash, which existing contribution changes to keep the plan affordable?”',
 'No assumed Reed current election, bracket, deduction, qualified-distribution status or after-tax result. Use actual model support; external budget reconciliation is separately labeled. New contributions are not conversions, and IRA rules are not automatically workplace rules. Verify save/readback without a provider election claim.',
 'Explain present cost, later purpose and affordability of the proposed election or mix.'),
('Tell each account what to buy',
 'After 4.7, read differently sized Alex accounts: $239,000 combined fund exposure within $555,000, not an average of 30% and 80%. Return explicitly to the Reed 60/34/6 comparison and $56,200 BTC difference. Compare new purchases before a cost-bearing taxable sale where appropriate. Future-only $1,000 BTC plus $605 taxable stocks uses the conditional $1,605 once.',
 '“The household target is not the purchase instruction for every account. Read the dollar holdings together, then decide what new money should buy here. This future route needs the card payments to end; it is not a funded purchase today.”',
 'Preserve current holdings/target/current contributions/future contributions/executed history separately. Verify menu, asset-class versus exact-security input, fees, overlaps, and the actual investment editor. No automatic target-to-trade, fake basis, in-kind retirement contribution or exact target-date guarantee.',
 'Each applicable current and future contribution has an amount, purpose, account, tax election and intended holding.'),
('Complete the outside instructions',
 'Use the existing action list for payroll, account opening, transfer and recurring purchase. Confirm start conditions and who acts. Read actual authorized example confirmations only when they exist; otherwise keep the outside action pending.',
 '“Changing the contribution and changing what it buys may be two instructions. When the first contribution happens, check both. Did the money reach the intended account, and did it buy the investment? The confirmation is what lets us update the plan from an intention to something actually done.”',
 'Verify all applicable instructions, not merely one sample. No live trade, bank transfer, payroll change or provider receipt is fabricated. Operational cash retains its job. Save and source/readback reflect the same chosen plan; a tax-sensitive sale with missing history goes to W05, not a made-up record.',
 'The complete portfolio and contribution plan can be explained and implemented through dated, verifiable outside actions.')
]
}
FINISH = {
'W01':'The current facts, initial retirement question and assumptions produce an answer the member can explain. Known limitations remain named. The next work is the fuller cash-flow review, not a claim that every later planning decision is complete.',
'W04':'The member can explain the whole portfolio, including why the non-Bitcoin portion exists, and trace every applicable contribution through purpose, amount, account and holding to an outside instruction. Target choice, verified access, executed action and actual result evidence remain separate.'
}
SETUP = {
'W01':'Use the unchanged Reed fixture plus a separately reviewed capture extension for missing dates, tax jurisdiction and mapping, debt schedules, benefits, payroll election, security identities and event details. Never treat software defaults as source facts. Record each chapter after its paired lesson using an isolated, authorized demo environment. No hosted write or live provider operation is authorized by this manuscript.',
'W04':'Carry forward W01 facts and the named reduced-spending W02/W03 comparison. Do not recreate accounts, revise the accepted Reserve, invent available cash or silently adopt a loan. The whole-portfolio illustration is separate from the unchanged Reeds. Actual account/target/contribution support and results must be verified on the approved redesign.'
}
