#!/usr/bin/env python3
"""[CORE COURSE ONLY] Combine every script into one readable .md for a full read-through.

    python3 tools/build-onefile.py   ->  ALL-SCRIPTS.md
"""
import re, os, glob

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
files = sorted(glob.glob(os.path.join(root, 'scripts', '*.md')))
files = [f for f in files if not any(k in os.path.basename(f) for k in ('README', 'VOICE-GUIDE'))]

# Module names come from the master. The hardcoded dict this replaces was wrong
# three ways at once: it mapped file prefix '01' to "Module 0" (off by one, and
# Module 0's own '00' files fell through to a literal "00" heading); it still
# called Module 3 "Allocation" and Module 4 "Debt" from before Debt moved ahead
# of Allocation; and it carried a "Module 10 — Plan Review" that no longer exists.
_master = open(os.path.join(root, 'MASTER-COURSE.md'), encoding='utf-8').read()
MODULES = {f'{int(m.group(2)):02d}': m.group(1).strip()
           for m in re.finditer(r'^# Unit \d+ · (Module (\d+)[^\n]*)$', _master, re.M)}

def kind(name):
    if 'WALKTHROUGH' in name: return 'WALKTHROUGH'
    if 'DEMO' in name:        return 'DEMO'
    return 'TEACH'

def lesson_no(name):
    m = re.match(r'(\d+)-(\d+)', name)
    return f'{int(m.group(1))}.{m.group(2)}' if m else '?'

def title_of(text, name):
    for ln in text.split('\n')[:6]:
        ln = ln.strip()
        if ln.startswith('# '):                     # walkthrough header
            return re.sub(r'^#\s*[\d.·+\s]*', '', ln).strip()
        if re.match(r'^\d+\.\d+\s+\S', ln):         # teleprompter line 2
            return ln.split(' ', 1)[1].strip()
    return os.path.basename(name)

def body(text):
    """Drop the teleprompter header block; keep everything spoken."""
    lines = text.split('\n')
    if lines and lines[0].startswith('TELEPROMPTER'):
        for i, ln in enumerate(lines):
            if set(ln.strip()) == {'='}:
                return '\n'.join(lines[i+1:]).strip()
    # walkthroughs open with their own H1 — drop it, the section heading covers it
    if lines and lines[0].startswith('# '):
        return '\n'.join(lines[1:]).strip()
    return text.strip()

entries, toc, cur = [], [], None
total_words = 0
for f in files:
    name = os.path.basename(f)
    raw  = open(f, encoding='utf-8').read()
    mod  = name[:2]
    if mod != cur:
        cur = mod
        toc.append(f'\n**{MODULES.get(mod, mod)}**\n')
        entries.append(f'\n\n---\n\n# {MODULES.get(mod, mod)}\n')
    no, k, ttl = lesson_no(name), kind(name), title_of(raw, name)
    b = body(raw)
    w = len(b.split()); total_words += w
    dictated = 'AUSTIN DICTATION' in raw[:1000]
    tag = ' · **AUSTIN DICTATION**' if dictated else ''
    mins = f' · ~{max(1, round(w/155))} min' if k == 'TEACH' else ''
    anchor = f'{no}-{k.lower()}'.replace('.', '-')
    toc.append(f'- [{no} · {ttl}](#{anchor}) — {k}{mins}{tag}')
    entries.append(
        f'\n<a id="{anchor}"></a>\n\n## {no} · {ttl}\n\n'
        f'`{name}` · {k}{mins} · {w:,} words{tag}\n\n{b}\n')

teach = sum(1 for f in files if kind(os.path.basename(f)) == 'TEACH')
head = (f'# Orange Plan Academy — every script, in film order\n\n'
        f'Generated from `scripts/` by `tools/build-onefile.py`. '
        f'**Do not edit this file** — edit the individual scripts and regenerate.\n\n'
        f'{len(files)} files · {teach} teach lessons · {len(files)-teach} walkthroughs/demos · '
        f'~{total_words:,} words · ~{round(total_words/155/60,1)} hours of teach+narration at 155 wpm\n\n'
        f'Teleprompter headers are stripped. Walkthroughs are DO/SEE/⚠ sheets, not scripts.\n\n'
        f'---\n\n## Contents\n' + '\n'.join(toc) + '\n')

open(os.path.join(root, 'ALL-SCRIPTS.md'), 'w', encoding='utf-8').write(head + ''.join(entries))
print(f'ALL-SCRIPTS.md — {len(files)} files, {total_words:,} words')
