#!/usr/bin/env python3
"""Surface every Advanced Library lesson at the bottom of its core module.

The client calls found the failure mode this fixes: advanced material that is
correctly optional but effectively invisible. A student cannot decide to skip
something they never learned exists.

So each core module ends with a generated block naming its advanced lessons and
the CONDITION that makes each one worth watching — the condition, not the topic,
is what lets someone stop. Conditions come from the `> **Gate.**` line each
advanced lesson already carries, so there is one place to edit them.

Advanced module N mirrors core module N. Both masters are read; the block is
rewritten between markers, so re-running is safe.

Run:  python3 tools/build-module-gates.py
"""
import os, re

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
core = open(os.path.join(root, 'MASTER-COURSE.md'), encoding='utf-8').read()
adv = open(os.path.join(root, 'MASTER-ADVANCED.md'), encoding='utf-8').read()

# --- advanced lessons, grouped by their advanced module number --------------
lessons = {}
units = [(m.group(1), m.group(2), m.start())
         for m in re.finditer(r'^# Advanced Module (\d+) — (.+)$', adv, re.M)]
for i, (num, name, start) in enumerate(units):
    end = units[i + 1][2] if i + 1 < len(units) else len(adv)
    seg = adv[start:end]
    out = []
    for lm in re.finditer(r'^## (\S+) (.+)$', seg, re.M):
        after = seg[lm.end():lm.end() + 1200]
        g = re.search(r'> \*\*Gate\.\*\*\s*(.+?)(?:\n\n|\n\*\*By the end)', after, re.S)
        cond = ' '.join(g.group(1).split()).replace('> ', '') if g else ''
        cond = re.sub(r'\s+', ' ', cond).strip()
        out.append((lm.group(1), lm.group(2), cond))
    if out:
        lessons[int(num)] = (name, out)

START, END = '<!-- ADVANCED-GATE:START -->', '<!-- ADVANCED-GATE:END -->'

# --- core module boundaries -------------------------------------------------
cunits = [(m.group(1), m.start()) for m in re.finditer(r'^# Unit \d+ · Module (\d+)[^\n]*$', core, re.M)]
inserted = 0
for i in range(len(cunits) - 1, -1, -1):          # backwards: offsets stay valid
    mod, start = int(cunits[i][0]), cunits[i][1]
    end = cunits[i + 1][1] if i + 1 < len(cunits) else len(core)
    if mod not in lessons:
        continue
    name, ls = lessons[mod]
    block = [START, '',
             '## Related advanced lessons', '',
             '**Your core plan is complete.** These are optional, and each one is',
             'worth watching only when its condition is true for you. Continue only if',
             'one of these describes your situation:', '']
    for num, title, cond in ls:
        block.append(f'- **{num} {title}**')
        block.append(f'  → *{cond}*' if cond else '  → *(no gate condition set — add one to MASTER-ADVANCED.md)*')
    block += ['',
              '*Generated by `tools/build-module-gates.py` from the Gate line on each',
              'advanced lesson. Edit the condition there, not here.*', '', END, '']
    seg = core[start:end]
    if START in seg:
        seg = re.sub(re.escape(START) + r'.*?' + re.escape(END), '\n'.join(block).strip(), seg, flags=re.S)
    else:
        seg = seg.rstrip() + '\n\n' + '\n'.join(block)
    core = core[:start] + seg + core[end:]
    inserted += 1

open(os.path.join(root, 'MASTER-COURSE.md'), 'w', encoding='utf-8').write(core)
missing = [f'A{m}' for m in lessons if any(not c for _, _, c in lessons[m][1])]
print(f'gate blocks written for {inserted} core modules'
      + (f'; NO GATE CONDITION on lessons in: {missing}' if missing else ''))
