#!/usr/bin/env python3
"""[CORE COURSE ONLY] Generate FILM-ORDER.md from scripts/.

⚠ FILM-ORDER.md is NOT a live production source. `PRODUCTION-CHECKLIST.md` is —
it carries the waves, the blocker status and the checkpoint reminders, and this
file has none of that. This is kept only as a flat one-line-per-script index,
and it stamps a banner saying so.

The module names used to be a hardcoded dict, and it was wrong in three separate
ways at once: it mapped file prefix '01' to "Module 0" (an off-by-one — '01' is
Module 1, and Module 0's files, prefixed '00', were not in the dict at all and
raised KeyError); it still called Module 3 "Allocation" and Module 4 "Debt" from
before Debt moved ahead of Allocation; and it carried a "Module 10 — Plan Review"
that no longer exists. Names now come from the master, so they cannot drift.

Run after any merge or renumber:  python3 tools/build-film-order.py
"""
import os, re, glob

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
master = open(os.path.join(root, 'MASTER-COURSE.md'), encoding='utf-8').read()

# '# Unit 3 · Module 2 — Cash Flow + Reserve' -> {'02': 'Module 2 — Cash Flow + Reserve'}
M = {}
for m in re.finditer(r'^# Unit \d+ · (Module (\d+)[^\n]*)$', master, re.M):
    M[f'{int(m.group(2)):02d}'] = m.group(1).strip()

out = ["# Film order",
       "",
       "> ⚠ **Not a production source.** This is a flat index of `scripts/` in file",
       "> order, nothing more. What to film, in what order, in which wave, and what is",
       "> currently blocked all live in **`PRODUCTION-CHECKLIST.md`**. Screen-capture",
       "> beats and app state live in **`SCREEN-SHOOT-LIST.md`**. Dictation order and",
       "> runtimes live in **`DICTATION-ORDER.md`**. Those three are the production set.",
       "",
       "Generated by `tools/build-film-order.py` from `scripts/`. Do not hand-edit.",
       "",
       "🎙 = prompter (teach) · 🖥 = screen capture · walkthroughs are narrated, not scripted.",
       ""]
cur = None
for f in sorted(glob.glob(os.path.join(root, 'scripts', '*.md'))):
    b = os.path.basename(f)
    if not b[0].isdigit():
        continue
    raw = open(f, encoding='utf-8').read()
    mod = b[:2]
    if mod != cur:
        cur = mod
        out += [f"## {M.get(mod, f'Module ?? (prefix {mod} is in no master unit)')}", ""]
    num = re.match(r'(\d+)-([\d\w-]+?)_', b)
    no = f"{int(num.group(1))}.{num.group(2)}"
    title = None
    for ln in raw.split('\n')[:6]:
        ln = ln.strip()
        if ln.startswith('# '):
            title = re.sub(r'^#\s*[\d.·+\s]*', '', ln)
            break
        if re.match(r'^\d+\.\S*\s+\S', ln):
            title = ln.split(' ', 1)[1]
            break
    icon = '🖥 CAPTURE' if re.search(r'WALKTHROUGH|DEMO', b) else '🎙 PROMPTER'
    dic = ' · **AUSTIN DICTATION**' if 'AUSTIN DICTATION' in raw[:400] else ''
    out.append(f"- [ ] **{no} {title}** — {icon} `scripts/{b}`{dic}")
    if re.search(r'WALKTHROUGH|DEMO', b):
        out.append("")
out.append("")
open(os.path.join(root, 'FILM-ORDER.md'), 'w', encoding='utf-8').write("\n".join(out))
print("FILM-ORDER.md regenerated")
