#!/usr/bin/env python3
"""[CORE COURSE ONLY] Generate FILM-ORDER.md from scripts/. Run after any merge or renumber."""
import os, re, glob
root=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
M={'01':'Module 0 — Start Here','02':'Module 1 — Foundation','03':'Module 2 — Cash Flow + Reserve',
'04':'Module 3 — Allocation','05':'Module 4 — Debt','06':'Module 5 — Tax','07':'Module 6 — Retirement Income',
'08':'Module 7 — Custody','09':'Module 8 — Estate','10':'Module 9 — Maintenance','11':'Module 10 — Plan Review'}
out=["# Film order","","Generated by `tools/build-film-order.py` from `scripts/`. Do not hand-edit.","",
     "🎙 = prompter (teach) · 🖥 = screen capture · walkthroughs are narrated, not scripted.",""]
cur=None
for f in sorted(glob.glob(os.path.join(root,'scripts','*.md'))):
    b=os.path.basename(f)
    if not b[0].isdigit(): continue
    raw=open(f,encoding='utf-8').read()
    mod=b[:2]
    if mod!=cur:
        cur=mod; out+=[f"## {M[mod]}",""]
    num=re.match(r'(\d+)-([\d\w-]+?)_',b); no=f"{int(num.group(1))}.{num.group(2)}"
    title=None
    for ln in raw.split('\n')[:6]:
        ln=ln.strip()
        if ln.startswith('# '): title=re.sub(r'^#\s*[\d.·\s]*','',ln); break
        if re.match(r'^\d+\.\S*\s+\S',ln): title=ln.split(' ',1)[1]; break
    icon='🖥 CAPTURE' if re.search(r'WALKTHROUGH|DEMO',b) else '🎙 PROMPTER'
    dic=' · **AUSTIN DICTATION**' if 'AUSTIN DICTATION' in raw[:400] else ''
    out.append(f"- [ ] **{no} {title}** — {icon} `scripts/{b}`{dic}")
    if b.endswith('.md') and re.search(r'WALKTHROUGH|DEMO',b): out.append("")
out.append("")
open(os.path.join(root,'FILM-ORDER.md'),'w',encoding='utf-8').write("\n".join(out))
print(f"FILM-ORDER.md regenerated")
