#!/usr/bin/env python3
"""Measure the course, and stamp the numbers into every doc that quotes them.

Three documents used to carry hand-typed counts (README, MASTER-COURSE,
FILMING-CHECKLIST). All three went stale the moment a lesson was trimmed, and
"I updated the header" is not the same as "the document is current" — which is
how a stamped README ended up still saying 246 minutes.

So the numbers live in exactly one place: measured here, written into marked
blocks. Anything between the markers is generated and will be overwritten.

    <!-- METRICS:START --> ... <!-- METRICS:END -->

Run after any trim:  python3 tools/course-metrics.py
Or check without writing:  python3 tools/course-metrics.py --check
"""
import os, re, sys, json

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHECK = '--check' in sys.argv


def measure(d):
    teach = sessions = 0
    tw = 0
    for f in sorted(os.listdir(d)):
        if not f.endswith('.md') or f in ('README.md', 'VOICE-GUIDE.md'):
            continue
        if 'WALKTHROUGH' in f or 'DEMO' in f:
            sessions += 1          # one SHEET = one continuous recording
            continue
        body = open(os.path.join(d, f), encoding='utf-8').read().split('=' * 60, 1)[-1]
        tw += len(body.split())
        teach += 1
    return teach, tw, sessions


# Capture LESSONS come from the master, not from the sheet count. Those two
# numbers are no longer equal: Module 1 publishes 1.4 and 1.5 as two lessons but
# is filmed in one session off one sheet. Counting sheets and calling the result
# "captures" is precisely how the README ended up claiming 9 walkthroughs + 1
# demo while the metrics block said 11.
core_master = open(os.path.join(root, 'MASTER-COURSE.md'), encoding='utf-8').read()
cap_titles = re.findall(r'^## \d+\.\d+ (Walkthrough|External demo)', core_master, re.M)
n_walk = sum(1 for t in cap_titles if t == 'Walkthrough')
n_demo = sum(1 for t in cap_titles if t == 'External demo')

core_n, core_w, core_sessions = measure(os.path.join(root, 'scripts'))
adv_n, adv_w, _ = measure(os.path.join(root, 'scripts', 'advanced'))
core_min, adv_min = core_w / 155, adv_w / 155

M = dict(core_n=core_n, core_min=round(core_min), core_h=round(core_min / 60, 1),
         core_w=core_w, core_caps=n_walk + n_demo, core_walkthroughs=n_walk,
         core_demos=n_demo, core_capture_sessions=core_sessions,
         adv_n=adv_n, adv_min=round(adv_min), adv_w=adv_w)

_demo_txt = (f' + {M["core_demos"]} external demo'
             + ('s' if M['core_demos'] != 1 else '')) if M['core_demos'] else ''
BLOCK = f"""<!-- METRICS:START -->
| | Lessons | Runtime |
|---|---|---|
| **Core** — Build Your Bitcoin Financial Plan (required) | {M['core_n']} teach | **{M['core_min']} min ({M['core_h']} h)** |
| **Advanced Library** — optional, gated per lesson | {M['adv_n']} teach | {M['adv_min']} min |

Plus {M['core_caps']} core screen captures ({M['core_walkthroughs']} walkthroughs{_demo_txt}),
narrated off the DO / SEE / ⚠ sheets rather than read. They are filmed in
{M['core_capture_sessions']} recording sessions — one sheet covers both Module 1 captures.

*Measured from `scripts/` at 155 wpm, captures counted from `MASTER-COURSE.md`.
Generated by `tools/course-metrics.py` — do not hand-edit this block.*
<!-- METRICS:END -->"""

# FILMING-CHECKLIST.md was retired as a live production source on 2026-08-08 and
# is kept as history, so it no longer gets stamped.
targets = ['README.md', 'MASTER-COURSE.md']
stale = []
for t in targets:
    p = os.path.join(root, t)
    s = open(p, encoding='utf-8').read()
    if 'METRICS:START' not in s:
        stale.append(f'{t}: no METRICS block'); continue
    new = re.sub(r'<!-- METRICS:START -->.*?<!-- METRICS:END -->',
                 BLOCK.replace('\\', '\\\\'), s, flags=re.S)
    if new != s:
        stale.append(t)
        if not CHECK:
            open(p, 'w', encoding='utf-8').write(new)

# Any bare runtime figure left outside a metrics block is a lie waiting to be read.
BAD = re.compile(r'\b(\d{3}) min(?:utes)? of (?:core |required )?teach', re.I)
for t in targets + ['DICTATION-ORDER.md', 'SCREEN-SHOOT-LIST.md', 'PRODUCTION-CHECKLIST.md']:
    p = os.path.join(root, t)
    if not os.path.exists(p):
        continue
    s = open(p, encoding='utf-8').read()
    outside = re.sub(r'<!-- METRICS:START -->.*?<!-- METRICS:END -->', '', s, flags=re.S)
    for m in BAD.finditer(outside):
        if int(m.group(1)) != M['core_min']:
            stale.append(f'{t}: stale runtime "{m.group(0)}" (now {M["core_min"]})')

print(json.dumps(M, indent=2))
if CHECK:
    print('STALE:', stale or 'none')
    sys.exit(1 if stale else 0)
print('stamped:', ', '.join(targets))
if stale:
    print('note:', stale)
