#!/usr/bin/env python3
"""Measure the course and stamp the numbers into every doc that quotes them.

The metrics live in one place and are written into marked blocks:

    <!-- METRICS:START --> ... <!-- METRICS:END -->

Run after any script change:  python3 tools/course-metrics.py
Check without writing:       python3 tools/course-metrics.py --check
"""
import os, re, sys, json

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHECK = '--check' in sys.argv


def measure(d):
    teach = sessions = 0
    words = 0
    for f in sorted(os.listdir(d)):
        if not f.endswith('.md') or f in ('README.md', 'VOICE-GUIDE.md'):
            continue
        if 'WALKTHROUGH' in f or 'DEMO' in f:
            sessions += 1
            continue
        body = open(os.path.join(d, f), encoding='utf-8').read().split('=' * 60, 1)[-1]
        words += len(body.split())
        teach += 1
    return teach, words, sessions


script_dir = os.path.join(root, 'scripts')
core_script_files = [
    f for f in os.listdir(script_dir)
    if f.endswith('.md') and f not in ('README.md', 'VOICE-GUIDE.md')
]
n_walk = sum('WALKTHROUGH' in f for f in core_script_files)
n_demo = sum('DEMO' in f for f in core_script_files)

core_n, core_w, core_sessions = measure(script_dir)
adv_n, adv_w, _ = measure(os.path.join(script_dir, 'advanced'))
core_min, adv_min = core_w / 155, adv_w / 155

M = dict(
    core_n=core_n,
    core_min=round(core_min),
    core_h=round(core_min / 60, 1),
    core_w=core_w,
    core_caps=n_walk + n_demo,
    core_walkthroughs=n_walk,
    core_demos=n_demo,
    core_capture_sessions=core_sessions,
    adv_n=adv_n,
    adv_min=round(adv_min),
    adv_w=adv_w,
)

_demo_txt = (
    f' + {M["core_demos"]} external demo'
    + ('s' if M['core_demos'] != 1 else '')
) if M['core_demos'] else ''

BLOCK = f"""<!-- METRICS:START -->
| | Lessons | Runtime |
|---|---|---|
| **Core** — Build Your Bitcoin Financial Plan (required) | {M['core_n']} teach | **{M['core_min']} min ({M['core_h']} h)** |
| **Advanced Library** — optional, gated per lesson | {M['adv_n']} teach | {M['adv_min']} min |

Plus {M['core_caps']} core screen captures ({M['core_walkthroughs']} walkthroughs{_demo_txt}),
narrated off the DO / SEE / ⚠ sheets rather than read. They are filmed in
{M['core_capture_sessions']} recording sessions.

*Measured from `scripts/` at 155 wpm. Generated by
`tools/course-metrics.py` — do not hand-edit this block.*
<!-- METRICS:END -->"""

targets = ['README.md', 'MASTER-COURSE.md']
stale = []
for target in targets:
    path = os.path.join(root, target)
    source = open(path, encoding='utf-8').read()
    if 'METRICS:START' not in source:
        stale.append(f'{target}: no METRICS block')
        continue
    rendered = re.sub(
        r'<!-- METRICS:START -->.*?<!-- METRICS:END -->',
        BLOCK.replace('\\', '\\\\'),
        source,
        flags=re.S,
    )
    if rendered != source:
        stale.append(target)
        if not CHECK:
            open(path, 'w', encoding='utf-8').write(rendered)

BAD = re.compile(r'\b(\d{3}) min(?:utes)? of (?:core |required )?teach', re.I)
for target in targets + ['DICTATION-ORDER.md', 'SCREEN-SHOOT-LIST.md', 'PRODUCTION-CHECKLIST.md']:
    path = os.path.join(root, target)
    if not os.path.exists(path):
        continue
    source = open(path, encoding='utf-8').read()
    outside = re.sub(r'<!-- METRICS:START -->.*?<!-- METRICS:END -->', '', source, flags=re.S)
    for match in BAD.finditer(outside):
        if int(match.group(1)) != M['core_min']:
            stale.append(f'{target}: stale runtime "{match.group(0)}" (now {M["core_min"]})')

print(json.dumps(M, indent=2))
if CHECK:
    print('STALE:', stale or 'none')
    sys.exit(1 if stale else 0)

print('stamped:', ', '.join(targets))
if stale:
    print('updated:', stale)
