#!/usr/bin/env python3
"""Audit spoken course scripts for contrastive-negation writing.

Austin's voice guide already rejects the "not A, but B" / "it isn't A, it's B"
copywriting move. This audit catches the same move when it is split across two
sentences, which the existing slop scanner did not see.

This tool is diagnostic. Every hit is a candidate for a human read. Safety,
legal, tax, custody, and misconception corrections may legitimately use a
negative statement when the negative itself carries the information.
"""
from __future__ import annotations

import glob
import os
import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "DIRECT-VOICE-AUDIT.md"


@dataclass(frozen=True)
class Hit:
    path: str
    line: int
    family: str
    text: str


SAME_SENTENCE = [
    re.compile(r"\b(?:isn'?t|aren'?t|is not|are not|wasn'?t|weren'?t|doesn'?t|does not|don'?t|do not)\b[^.!?]{2,120}\bbut\b", re.I),
    re.compile(r"\bnot\s+(?:just\s+)?(?:a|an|the)?\s*[^.!?]{2,80},\s*(?:but|it'?s|they'?re|that'?s|instead)\b", re.I),
    re.compile(r"\bnot because\b[^.!?]{2,100}\bbut because\b", re.I),
    re.compile(r"\bless about\b[^.!?]{2,80}\bmore about\b", re.I),
    re.compile(r"\bit'?s not that\b[^.!?]{2,100}\bit'?s that\b", re.I),
]

NEGATION_OPENERS = re.compile(
    r"^(?:This|That|It|The goal|The point|The purpose|The answer|The result|You|We|I)\s+"
    r"(?:isn'?t|aren'?t|is not|are not|wasn'?t|weren'?t|doesn'?t|does not|don'?t|do not|didn'?t|did not)\b",
    re.I,
)

HIGH_FRICTION = re.compile(
    r"\b(?:doesn'?t mean|does not mean|not automatically|do not automatically|"
    r"I do not mean|I don'?t mean|I do not think|I don'?t think|"
    r"The goal is not|The point is not|The purpose is not|This is not|That is not)\b",
    re.I,
)

NEXT_AFFIRMATIVE = re.compile(
    r"^(?:It|They|This|That|The|You|We|A|An|Instead|Rather|What|Your|Orange Plan|Foundation|Integration|Optimization|Sovereign)\b",
    re.I,
)


# Safety/compliance lines still appear in the report. They are labeled separately
# so the editor does not flatten a necessary boundary merely to satisfy a style
# preference.
SAFETY = re.compile(
    r"\b(?:seed phrase|private key|passphrase|PIN|password|guarantee|financial advice|"
    r"tax advice|legal advice|insurance|execute|execution|trade|loan|withdrawal|"
    r"probability|chance of going broke|chance you go broke|forecast|prediction)\b",
    re.I,
)


def sentence_spans(line: str) -> list[str]:
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", line.strip()) if s.strip()]


def targets() -> list[Path]:
    files = [Path(p) for p in glob.glob(str(ROOT / "scripts" / "*.md"))]
    files += [Path(p) for p in glob.glob(str(ROOT / "scripts" / "advanced" / "*.md"))]
    return [p for p in sorted(files) if p.name not in {"README.md", "VOICE-GUIDE.md"}]


def main() -> None:
    hits: list[Hit] = []
    for path in targets():
        rel = path.relative_to(ROOT).as_posix()
        for line_no, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            line = raw.strip()
            if not line or line.startswith(("#", "|", "```", "TELEPROMPTER", "==", "**DO**", "**SEE**", "**ENTER**", "**SAVE**", "**POINT", "**WATCH", "**⚠")):
                continue

            family = "safety/compliance candidate" if SAFETY.search(line) else "direct-voice candidate"
            if any(rx.search(line) for rx in SAME_SENTENCE):
                hits.append(Hit(rel, line_no, family + " · same-sentence reversal", line))

            if HIGH_FRICTION.search(line):
                hits.append(Hit(rel, line_no, family + " · negation-led explanation", line))

            sents = sentence_spans(line)
            for left, right in zip(sents, sents[1:]):
                if (NEGATION_OPENERS.search(left) or HIGH_FRICTION.search(left)) and NEXT_AFFIRMATIVE.search(right):
                    hits.append(Hit(rel, line_no, family + " · cross-sentence reversal", f"{left} {right}"))

    # Deduplicate exact same candidate caught by more than one detector.
    unique: list[Hit] = []
    seen: set[tuple[str, int, str]] = set()
    for hit in hits:
        key = (hit.path, hit.line, hit.text)
        if key not in seen:
            seen.add(key)
            unique.append(hit)

    by_file: dict[str, list[Hit]] = {}
    for hit in unique:
        by_file.setdefault(hit.path, []).append(hit)

    direct = sum("direct-voice candidate" in h.family for h in unique)
    safety = sum("safety/compliance candidate" in h.family for h in unique)
    out = [
        "# Direct-voice audit",
        "",
        "> Generated by `tools/direct-voice-audit.py`. Every line below is a",
        "> candidate for a human read, not an automatic deletion. The goal is to",
        "> replace copywriting-style reversals with the useful affirmative fact while",
        "> preserving negatives that carry safety, legal, tax, or misconception value.",
        "",
        f"- **{direct}** ordinary direct-voice candidates",
        f"- **{safety}** safety/compliance candidates",
        f"- **{len(unique)}** total candidates across **{len(by_file)}** files",
        "",
        "## Editing rule",
        "",
        "Use the affirmative sentence when it carries the whole idea. Keep a negative",
        "only when the viewer could make a materially unsafe or incorrect decision",
        "without hearing exactly what is excluded.",
        "",
    ]
    for path, file_hits in sorted(by_file.items()):
        out += [f"## `{path}`", ""]
        for hit in file_hits:
            out += [f"- **L{hit.line} · {hit.family}**", f"  - {hit.text}"]
        out.append("")

    OUT.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} with {len(unique)} candidates")


if __name__ == "__main__":
    main()
